In [112]:

# Import libraries
from pathlib import Path

import pandas as pd

In [113]:

# Define project directory
project_dir = Path.cwd().parent

# Define source file path
file_path = (
    project_dir
    / "data"
    / "raw"
    / "bmelh_ble_versorgungsbilanzen_1990-2025_weichweizen_gerste_kartoffel"
    / "ble_versorgungsbilanzen_1991-2025"
    / "01_ready_to_clean_ble_supply_balance_all_products_1991-2025.xls"
)

# Check whether the source file exists
print(f"Project directory: {project_dir}")
print(f"Source file exists: {file_path.exists()}")
print(f"Source file path: {file_path}")

Project directory: c:\Users\incog\Desktop\Portfolio_Project_Agriculture
Source file exists: True
Source file path: c:\Users\incog\Desktop\Portfolio_Project_Agriculture\data\raw\bmelh_ble_versorgungsbilanzen_1990-2025_weichweizen_gerste_kartoffel\ble_versorgungsbilanzen_1991-2025\01_ready_to_clean_ble_supply_balance_all_products_1991-2025.xls

In [114]:

# Load source data
df = pd.read_excel(file_path, engine="xlrd")

# Display the first five rows
display(df.head())

,Wirtschaftsjahr,Bilanz Produkt,Bilanz Oberbegriff,Bilanz Position,Bilanz Einheit,Bilanz Wert
0,1991/92,Gerste,Detailposition,Inlandsverwendung insgesamt,1 000 t Produktgewicht,10637.0
1,1991/92,Gerste,Detailposition,Nahrungsverbrauch in Getreidewert,1 000 t Getreidewert,10.0
2,1991/92,Gerste,Detailposition,Industrielle Verwertung für Energie,1 000 t Produktgewicht,NaN
3,1991/92,Gerste,Detailposition,Saatgut,1 000 t Produktgewicht,388.0
4,1991/92,Gerste,Detailposition,Industrielle Verwertung,1 000 t Produktgewicht,2671.0

In [115]:

# Inspect dataset dimensions
print(f"Number of rows: {df.shape[0]}")
print(f"Number of columns: {df.shape[1]}")

# Inspect column names
print("\nColumn names:")
print(df.columns.tolist())

# Inspect data types and non-null values
print("\nDataset information:")
df.info()

Number of rows: 1646
Number of columns: 6

Column names:
['Wirtschaftsjahr', 'Bilanz Produkt', 'Bilanz Oberbegriff', 'Bilanz Position', 'Bilanz Einheit', 'Bilanz Wert']

Dataset information:
<class 'pandas.DataFrame'>
RangeIndex: 1646 entries, 0 to 1645
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Wirtschaftsjahr     1646 non-null   str
 1   Bilanz Produkt      1646 non-null   str
 2   Bilanz Oberbegriff  1646 non-null   str
 3   Bilanz Position     1646 non-null   str
 4   Bilanz Einheit      1646 non-null   str
 5   Bilanz Wert         1582 non-null   float64
dtypes: float64(1), str(5)
memory usage: 77.3 KB

In [116]:

# Display the first ten rows
display(df.head(10))

,Wirtschaftsjahr,Bilanz Produkt,Bilanz Oberbegriff,Bilanz Position,Bilanz Einheit,Bilanz Wert
0,1991/92,Gerste,Detailposition,Inlandsverwendung insgesamt,1 000 t Produktgewicht,10637.00000
1,1991/92,Gerste,Detailposition,Nahrungsverbrauch in Getreidewert,1 000 t Getreidewert,10.00000
2,1991/92,Gerste,Detailposition,Industrielle Verwertung für Energie,1 000 t Produktgewicht,NaN
3,1991/92,Gerste,Detailposition,Saatgut,1 000 t Produktgewicht,388.00000
4,1991/92,Gerste,Detailposition,Industrielle Verwertung,1 000 t Produktgewicht,2671.00000
5,1991/92,Gerste,Detailposition,Verluste,1 000 t Produktgewicht,351.00000
6,1991/92,Gerste,Detailposition,Nahrungsverbrauch Ausbeute in %,%,80.00000
7,1991/92,Gerste,Detailposition,Futter,1 000 t Produktgewicht,7217.00000
8,1991/92,Gerste,Detailposition,Nahrungsverbrauch in Getreidewert in kg je Kopf,1 000 t Getreidewert,NaN
9,1991/92,Gerste,Selbstversorgungsgrad,Selbstversorgungsgrad in %,%,136.26022

In [117]:

# Check missing values
print("Missing values per column:")
display(df.isna().sum().to_frame(name="Missing values"))

# Check duplicate rows
duplicate_count = df.duplicated().sum()
print(f"\nNumber of duplicate rows: {duplicate_count}")

# Check unique values per column
print("\nNumber of unique values per column:")
display(df.nunique().to_frame(name="Unique values"))

Missing values per column:

                    Missing values
Wirtschaftsjahr                  0
Bilanz Produkt                   0
Bilanz Oberbegriff               0
Bilanz Position                  0
Bilanz Einheit                   0
Bilanz Wert                     64

Number of duplicate rows: 0

Number of unique values per column:

                    Unique values
Wirtschaftsjahr                35
Bilanz Produkt                  3
Bilanz Oberbegriff             12
Bilanz Position                26
Bilanz Einheit                  8
Bilanz Wert                  1420

In [118]:

# Inspect rows with missing balance values
missing_values = (
    df.loc[
        df["Bilanz Wert"].isna(),
        [
            "Wirtschaftsjahr",
            "Bilanz Produkt",
            "Bilanz Oberbegriff",
            "Bilanz Position",
            "Bilanz Einheit",
        ],
    ]
    .sort_values(
        ["Bilanz Produkt", "Bilanz Position", "Wirtschaftsjahr"]
    )
)

# Display all rows with missing values
display(missing_values)

,Wirtschaftsjahr,Bilanz Produkt,Bilanz Oberbegriff,Bilanz Position,Bilanz Einheit
2,1991/92,Gerste,Detailposition,Industrielle Verwertung für Energie,1 000 t Produktgewicht
19,1992/93,Gerste,Detailposition,Industrielle Verwertung für Energie,1 000 t Produktgewicht
36,1993/94,Gerste,Detailposition,Industrielle Verwertung für Energie,1 000 t Produktgewicht
53,1994/95,Gerste,Detailposition,Industrielle Verwertung für Energie,1 000 t Produktgewicht
70,1995/96,Gerste,Detailposition,Industrielle Verwertung für Energie,1 000 t Produktgewicht
...,...,...,...,...,...
1246,2001/02,Weichweizen,Detailposition,Nahrungsverbrauch in Getreidewert in kg je Kopf,Kilogramm Getreidewert
1263,2002/03,Weichweizen,Detailposition,Nahrungsverbrauch in Getreidewert in kg je Kopf,Kilogramm Getreidewert
1280,2003/04,Weichweizen,Detailposition,Nahrungsverbrauch in Getreidewert in kg je Kopf,Kilogramm Getreidewert
1297,2004/05,Weichweizen,Detailposition,Nahrungsverbrauch in Getreidewert in kg je Kopf,Kilogramm Getreidewert
1314,2005/06,Weichweizen,Detailposition,Nahrungsverbrauch in Getreidewert in kg je Kopf,Kilogramm Getreidewert

In [119]:

# Summarize missing values by product and balance position
missing_summary = (
    df.loc[df["Bilanz Wert"].isna()]
    .groupby(
        [
            "Bilanz Produkt",
            "Bilanz Oberbegriff",
            "Bilanz Position",
            "Bilanz Einheit",
        ],
        dropna=False,
    )
    .size()
    .reset_index(name="Missing values")
    .sort_values(
        ["Bilanz Produkt", "Bilanz Position"]
    )
)

display(missing_summary)

,Bilanz Produkt,Bilanz Oberbegriff,Bilanz Position,Bilanz Einheit,Missing values
0,Gerste,Detailposition,Industrielle Verwertung für Energie,1 000 t Produktgewicht,15
1,Gerste,Detailposition,Nahrungsverbrauch in Getreidewert in kg je Kopf,1 000 t Getreidewert,15
2,Kartoffeln,Bestandsänderung,Bestandsänderung,1 000 t Produktgewicht,4
3,Weichweizen,Detailposition,Industrielle Verwertung für Energie,1 000 t Produktgewicht,15
4,Weichweizen,Detailposition,Nahrungsverbrauch in Getreidewert in kg je Kopf,Kilogramm Getreidewert,15

In [120]:

# Count missing values by product, balance position, and year
missing_by_year = (
    df.loc[df["Bilanz Wert"].isna()]
    .groupby(
        [
            "Bilanz Produkt",
            "Bilanz Position",
            "Wirtschaftsjahr",
        ],
        dropna=False,
    )
    .size()
    .reset_index(name="Missing values")
    .sort_values(
        [
            "Bilanz Produkt",
            "Bilanz Position",
            "Wirtschaftsjahr",
        ]
    )
)

display(missing_by_year)

,Bilanz Produkt,Bilanz Position,Wirtschaftsjahr,Missing values
0,Gerste,Industrielle Verwertung für Energie,1991/92,1
1,Gerste,Industrielle Verwertung für Energie,1992/93,1
2,Gerste,Industrielle Verwertung für Energie,1993/94,1
3,Gerste,Industrielle Verwertung für Energie,1994/95,1
4,Gerste,Industrielle Verwertung für Energie,1995/96,1
...,...,...,...,...
59,Weichweizen,Nahrungsverbrauch in Getreidewert in kg je Kopf,2001/02,1
60,Weichweizen,Nahrungsverbrauch in Getreidewert in kg je Kopf,2002/03,1
61,Weichweizen,Nahrungsverbrauch in Getreidewert in kg je Kopf,2003/04,1
62,Weichweizen,Nahrungsverbrauch in Getreidewert in kg je Kopf,2004/05,1
63,Weichweizen,Nahrungsverbrauch in Getreidewert in kg je Kopf,2005/06,1

In [121]:

# Summarize missing year ranges by product and balance position
missing_year_ranges = (
    df.loc[df["Bilanz Wert"].isna()]
    .groupby(
        ["Bilanz Produkt", "Bilanz Position"],
        dropna=False,
    )
    .agg(
        first_missing_year=("Wirtschaftsjahr", "min"),
        last_missing_year=("Wirtschaftsjahr", "max"),
        number_of_missing_years=("Wirtschaftsjahr", "nunique"),
    )
    .reset_index()
)

display(missing_year_ranges)

,Bilanz Produkt,Bilanz Position,first_missing_year,last_missing_year,number_of_missing_years
0,Gerste,Industrielle Verwertung für Energie,1991/92,2005/06,15
1,Gerste,Nahrungsverbrauch in Getreidewert in kg je Kopf,1991/92,2005/06,15
2,Kartoffeln,Bestandsänderung,2018/19,2021/22,4
3,Weichweizen,Industrielle Verwertung für Energie,1991/92,2005/06,15
4,Weichweizen,Nahrungsverbrauch in Getreidewert in kg je Kopf,1991/92,2005/06,15

In [122]:

# Count records by product
product_counts = (
    df.groupby("Bilanz Produkt")
    .size()
    .reset_index(name="Number of records")
    .sort_values("Bilanz Produkt")
)

display(product_counts)

# Check whether all products have the same number of records
same_record_count = product_counts["Number of records"].nunique() == 1

print(f"All products have the same number of records: {same_record_count}")

  Bilanz Produkt  Number of records
0         Gerste                578
1     Kartoffeln                490
2    Weichweizen                578

All products have the same number of records: False

In [123]:
# Data quality note: The combined dataset contains 1,646 records: 578 for barley, 490 for potatoes, and 578 for soft wheat. The differences in record counts were checked against the original source data and were confirmed to exist in the raw data. Therefore, the differences were not caused by the data consolidation process. Missing values are retained for further investigation rather than being automatically replaced or removed.

In [124]:
duplicate_count = df.duplicated().sum()
print(f"Number of duplicate rows: {duplicate_count}")

Number of duplicate rows: 0

In [125]:
# Check year coverage by product
year_coverage = (
    df.groupby("Bilanz Produkt")
    .agg(
        Number_of_records=("Wirtschaftsjahr", "size"),
        Unique_years=("Wirtschaftsjahr", "nunique"),
        First_year=("Wirtschaftsjahr", "min"),
        Last_year=("Wirtschaftsjahr", "max"),
    )
    .reset_index()
)

display(year_coverage)

  Bilanz Produkt  Number_of_records  Unique_years First_year Last_year
0         Gerste                578            34    1991/92   2024/25
1     Kartoffeln                490            35    1990/91   2024/25
2    Weichweizen                578            34    1991/92   2024/25

In [126]:
# Remove financial year 1990/91
df = df[df["Wirtschaftsjahr"] != "1990/91"].copy()

In [127]:
# Check year coverage by product
year_coverage = (
    df.groupby("Bilanz Produkt")
    .agg(
        Number_of_records=("Wirtschaftsjahr", "size"),
        Unique_years=("Wirtschaftsjahr", "nunique"),
        First_year=("Wirtschaftsjahr", "min"),
        Last_year=("Wirtschaftsjahr", "max"),
    )
    .reset_index()
)

display(year_coverage)

  Bilanz Produkt  Number_of_records  Unique_years First_year Last_year
0         Gerste                578            34    1991/92   2024/25
1     Kartoffeln                476            34    1991/92   2024/25
2    Weichweizen                578            34    1991/92   2024/25

In [128]:
# Check the dataset dimensions
print(df.shape)

(1632, 6)

In [129]:
# Count records per product and financial year
records_per_year = (
    df.groupby(["Wirtschaftsjahr", "Bilanz Produkt"])
    .size()
    .unstack(fill_value=0)
    .sort_index()
)

display(records_per_year)

Bilanz Produkt   Gerste  Kartoffeln  Weichweizen
Wirtschaftsjahr
1991/92              17          14           17
1992/93              17          14           17
1993/94              17          14           17
1994/95              17          14           17
1995/96              17          14           17
1996/97              17          14           17
1997/98              17          14           17
1998/99              17          14           17
1999/00              17          14           17
2000/01              17          14           17
2001/02              17          14           17
2002/03              17          14           17
2003/04              17          14           17
2004/05              17          14           17
2005/06              17          14           17
2006/07              17          14           17
2007/08              17          14           17
2008/09              17          14           17
2009/10              17          14           17
2010/11              17          14           17
2011/12              17          14           17
2012/13              17          14           17
2013/14              17          14           17
2014/15              17          14           17
2015/16              17          14           17
2016/17              17          14           17
2017/18              17          14           17
2018/19              17          14           17
2019/20              17          14           17
2020/21              17          14           17
2021/22              17          14           17
2022/23              17          14           17
2023/24              17          14           17
2024/25              17          14           17

In [130]:

# Compare balance positions across products for a common year
comparison_year = "1991/92"

position_columns = [
    "Bilanz Oberbegriff",
    "Bilanz Position",
    "Bilanz Einheit",
]

year_df = df.loc[
    df["Wirtschaftsjahr"] == comparison_year,
    ["Bilanz Produkt"] + position_columns,
].copy()

# Normalize whitespace for comparison only
for column in position_columns:
    year_df[column] = (
        year_df[column]
        .astype("string")
        .str.replace(r"\s+", " ", regex=True)
        .str.strip()
    )

# Extract unique balance positions for each product
positions_by_product = {}

for product in ["Gerste", "Weichweizen", "Kartoffeln"]:
    positions = (
        year_df.loc[
            year_df["Bilanz Produkt"] == product,
            position_columns,
        ]
        .drop_duplicates()
        .sort_values(position_columns)
        .reset_index(drop=True)
    )

    positions_by_product[product] = positions

    print(f"\n{product}: {len(positions)} unique balance positions")
    display(positions)

Gerste: 17 unique balance positions

,Bilanz Oberbegriff,Bilanz Position,Bilanz Einheit
0,Anfangsbestand,Anfangsbestand,1 000 t Produktgewicht
1,Ausfuhr,Ausfuhr,1 000 t Produktgewicht
2,Detailposition,Futter,1 000 t Produktgewicht
3,Detailposition,Industrielle Verwertung,1 000 t Produktgewicht
4,Detailposition,Industrielle Verwertung für Energie,1 000 t Produktgewicht
5,Detailposition,Inlandsverwendung insgesamt,1 000 t Produktgewicht
6,Detailposition,Nahrungsverbrauch Ausbeute in %,%
7,Detailposition,Nahrungsverbrauch in Getreidewert,1 000 t Getreidewert
8,Detailposition,Nahrungsverbrauch in Getreidewert in kg je Kopf,1 000 t Getreidewert
9,Detailposition,Saatgut,1 000 t Produktgewicht
10,Detailposition,Verluste,1 000 t Produktgewicht
11,Einfuhr,Einfuhr,1 000 t Produktgewicht
12,Endbestand,Endbestand,1 000 t Produktgewicht
13,Produktion,Verwendbare Erzeugung,1 000 t Produktgewicht
14,Selbstversorgungsgrad,Selbstversorgungsgrad in %,%
15,Verbrauch,Nahrungsverbrauch in Produktgewicht,1 000 t Produktgewicht
16,Verbrauch je Kopf,Nahrungsverbrauch in Produktgewicht in kg je Kopf,Kilogramm Mehlwert

Weichweizen: 17 unique balance positions

,Bilanz Oberbegriff,Bilanz Position,Bilanz Einheit
0,Anfangsbestand,Anfangsbestand,1 000 t Produktgewicht
1,Ausfuhr,Ausfuhr,1 000 t Produktgewicht
2,Detailposition,Futter,1 000 t Produktgewicht
3,Detailposition,Industrielle Verwertung,1 000 t Produktgewicht
4,Detailposition,Industrielle Verwertung für Energie,1 000 t Produktgewicht
5,Detailposition,Inlandsverwendung insgesamt,1 000 t Produktgewicht
6,Detailposition,Nahrungsverbrauch Ausbeute in %,%
7,Detailposition,Nahrungsverbrauch in Getreidewert,1 000 t Getreidewert
8,Detailposition,Nahrungsverbrauch in Getreidewert in kg je Kopf,Kilogramm Getreidewert
9,Detailposition,Saatgut,1 000 t Produktgewicht
10,Detailposition,Verluste,1 000 t Produktgewicht
11,Einfuhr,Einfuhr,1 000 t Produktgewicht
12,Endbestand,Endbestand,1 000 t Produktgewicht
13,Produktion,Verwendbare Erzeugung,1 000 t Produktgewicht
14,Selbstversorgungsgrad,Selbstversorgungsgrad in %,%
15,Verbrauch,Nahrungsverbrauch in Produktgewicht,1 000 t Produktgewicht
16,Verbrauch je Kopf,Nahrungsverbrauch in Produktgewicht in kg je Kopf,Kilogramm Mehlwert

Kartoffeln: 14 unique balance positions

,Bilanz Oberbegriff,Bilanz Position,Bilanz Einheit
0,Ausfuhr,Ausfuhr,1 000 t Produktgewicht
1,Bestandsänderung,Bestandsänderung,1 000 t Produktgewicht
2,Detailposition,Futter,1 000 t Produktgewicht
3,Detailposition,Industrielle Verwertung,1 000 t Produktgewicht
4,Detailposition,Inlandsverwendung,1 000 t Produktgewicht
5,Detailposition,Nahrungsverbrauch Kartoffelerzeugnisse,Kilogramm Frischkartoffelwert
6,Detailposition,Saatgut,1 000 t Produktgewicht
7,Detailposition,Verluste,1 000 t Produktgewicht
8,Einfuhr,Einfuhr,1 000 t Produktgewicht
9,Gesamterzeugung,Gesamterzeugung,1 000 t Produktgewicht
10,Selbstversorgungsgrad,Selbstversorgungsgrad in %,%
11,Verbrauch,Nahrungsverbrauch,1 000 t Produktgewicht
12,Verbrauch je Kopf,Nahrungsverbrauch in kg je Kopf,Kilogramm Produktgewicht
13,Verwendbare Erzeugung,Verwendbare Erzeugung,1 000 t Produktgewicht

In [131]:
# Data quality note: The dataset contains 17 records per year for barley and soft wheat and 14 records per year for potatoes. A comparison of balance positions for the financial year 1991/92 showed that the product balances differ in their structure and include product-specific positions and differently named categories. The differences in record counts were also verified against the original source data. No records have been deleted, and no missing values have been replaced. The original data structure is retained for further analysis.

In [132]:
# Count records by product
product_counts = df["Bilanz Produkt"].value_counts().sort_index()

display(product_counts)

Bilanz Produkt
Gerste         578
Kartoffeln     476
Weichweizen    578
Name: count, dtype: int64

In [67]:
# Standardize whitespace in text columns
text_columns = df.select_dtypes(include=["str"]).columns

for column in text_columns:
    df[column] = (
        df[column]
        .str.replace(r"\s+", " ", regex=True)
        .str.strip()
    )

# Check dataset dimensions
print(f"Dataset shape: {df.shape}")

Dataset shape: (1632, 6)

In [133]:
# Final data quality checks
print(f"Number of rows: {df.shape[0]}")
print(f"Number of columns: {df.shape[1]}")
print(f"Duplicate rows: {df.duplicated().sum()}")
print(f"Missing values in Bilanz Wert: {df['Bilanz Wert'].isna().sum()}")

# Count records by product
display(df["Bilanz Produkt"].value_counts().sort_index())

# Inspect data types
display(df.dtypes)

Number of rows: 1632
Number of columns: 6
Duplicate rows: 0
Missing values in Bilanz Wert: 64

Bilanz Produkt
Gerste         578
Kartoffeln     476
Weichweizen    578
Name: count, dtype: int64

Wirtschaftsjahr           str
Bilanz Produkt            str
Bilanz Oberbegriff        str
Bilanz Position           str
Bilanz Einheit            str
Bilanz Wert           float64
dtype: object

In [134]:
%pip install openpyxl

Requirement already satisfied: openpyxl in c:\Users\incog\Desktop\Portfolio_Project_Agriculture\.venv\Lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\Users\incog\Desktop\Portfolio_Project_Agriculture\.venv\Lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

In [135]:
# Save the cleaned dataset
output_dir = project_dir / "data" / "processed"
output_dir.mkdir(parents=True, exist_ok=True)

output_path = output_dir / "ble_cleaned_supply_balance_1991-2025.xlsx"
df.to_excel(output_path, index=False)

print(f"File saved: {output_path}")

File saved: c:\Users\incog\Desktop\Portfolio_Project_Agriculture\data\processed\ble_cleaned_supply_balance_1991-2025.xlsx

In [136]:

from pathlib import Path
import pandas as pd

# Define project directory
project_dir = Path.cwd().parent

# Check project directory
print(f"Project directory: {project_dir}")
print(f"Project directory exists: {project_dir.exists()}")

Project directory: c:\Users\incog\Desktop\Portfolio_Project_Agriculture
Project directory exists: True

In [137]:

import pandas as pd
from pathlib import Path

# Define project directory
project_dir = Path.cwd().parent

# Define path to the cleaned dataset
input_path = (
    project_dir
    / "data"
    / "processed"
    / "ble_cleaned_supply_balance_1991-2025.xlsx"
)

# Check whether the cleaned file exists
if input_path.exists():
    # Load the cleaned dataset
    df = pd.read_excel(input_path)

    # Display information about the dataset
    print("Cleaned dataset loaded successfully!")
    print(f"File path: {input_path}")
    print(f"Number of rows: {df.shape[0]}")
    print(f"Number of columns: {df.shape[1]}")

    # Display column names
    print("\nColumn names:")
    print(df.columns.tolist())

    # Display the first five rows
    display(df.head())

else:
    print("Error: The cleaned dataset was not found.")
    print(f"Expected file path: {input_path}")

Cleaned dataset loaded successfully!
File path: c:\Users\incog\Desktop\Portfolio_Project_Agriculture\data\processed\ble_cleaned_supply_balance_1991-2025.xlsx
Number of rows: 1632
Number of columns: 6

Column names:
['Wirtschaftsjahr', 'Bilanz Produkt', 'Bilanz Oberbegriff', 'Bilanz Position', 'Bilanz Einheit', 'Bilanz Wert']

,Wirtschaftsjahr,Bilanz Produkt,Bilanz Oberbegriff,Bilanz Position,Bilanz Einheit,Bilanz Wert
0,1991/92,Gerste,Detailposition,Inlandsverwendung insgesamt,1 000 t Produktgewicht,10637.0
1,1991/92,Gerste,Detailposition,Nahrungsverbrauch in Getreidewert,1 000 t Getreidewert,10.0
2,1991/92,Gerste,Detailposition,Industrielle Verwertung für Energie,1 000 t Produktgewicht,NaN
3,1991/92,Gerste,Detailposition,Saatgut,1 000 t Produktgewicht,388.0
4,1991/92,Gerste,Detailposition,Industrielle Verwertung,1 000 t Produktgewicht,2671.0

In [138]:

import pandas as pd
import numpy as np

# 1. Define the required balance positions
required_positions = [
    "Einfuhr",
    "Ausfuhr",
    "Inlandsverwendung insgesamt",
    "Gesamterzeugung",
]

# 2. Select the required rows
selected = df[
    df["Bilanz Position"].isin(required_positions)
].copy()

# 3. Reshape the data by year and product
quota_data = selected.pivot_table(
    index=["Wirtschaftsjahr", "Bilanz Produkt"],
    columns="Bilanz Position",
    values="Bilanz Wert",
    aggfunc="first"
)

# 4. Calculate the ratios
quota_data["Importquote"] = (
    quota_data["Einfuhr"]
    / quota_data["Inlandsverwendung insgesamt"]
    * 100
)

quota_data["Exportquote"] = (
    quota_data["Ausfuhr"]
    / quota_data["Gesamterzeugung"]
    * 100
)

# 5. Exclude undefined or infinite results
quota_data[["Importquote", "Exportquote"]] = (
    quota_data[["Importquote", "Exportquote"]]
    .replace([np.inf, -np.inf], np.nan)
)

# 6. Convert the ratios into additional balance rows
new_rows = []

for (year, product), row in quota_data.iterrows():
    for position in ["Importquote", "Exportquote"]:
        value = row[position]

        if pd.notna(value):
            new_rows.append({
                "Wirtschaftsjahr": year,
                "Bilanz Produkt": product,
                "Bilanz Oberbegriff": "Berechnete Kennzahl",
                "Bilanz Position": position,
                "Bilanz Einheit": "%",
                "Bilanz Wert": value
            })

# 7. Append the new rows without modifying the original df
df_with_quotas = pd.concat(
    [df, pd.DataFrame(new_rows, columns=df.columns)],
    ignore_index=True
)

# 8. Display the calculated ratios
quota_results = df_with_quotas[
    df_with_quotas["Bilanz Position"].isin(
        ["Importquote", "Exportquote"]
    )
].copy()

display(
    quota_results.sort_values(
        ["Bilanz Produkt", "Wirtschaftsjahr", "Bilanz Position"]
    ).round({"Bilanz Wert": 2})
)

# 9. Verify the result
print(f"Original rows: {len(df)}")
print(f"Added quota rows: {len(new_rows)}")
print(f"Extended dataset rows: {len(df_with_quotas)}")

,Wirtschaftsjahr,Bilanz Produkt,Bilanz Oberbegriff,Bilanz Position,Bilanz Einheit,Bilanz Wert
1632,1991/92,Gerste,Berechnete Kennzahl,Importquote,%,11.59
1635,1992/93,Gerste,Berechnete Kennzahl,Importquote,%,9.86
1638,1993/94,Gerste,Berechnete Kennzahl,Importquote,%,11.91
1641,1994/95,Gerste,Berechnete Kennzahl,Importquote,%,12.35
1644,1995/96,Gerste,Berechnete Kennzahl,Importquote,%,14.89
...,...,...,...,...,...,...
1721,2020/21,Weichweizen,Berechnete Kennzahl,Importquote,%,28.79
1724,2021/22,Weichweizen,Berechnete Kennzahl,Importquote,%,31.99
1727,2022/23,Weichweizen,Berechnete Kennzahl,Importquote,%,31.79
1730,2023/24,Weichweizen,Berechnete Kennzahl,Importquote,%,39.05
1733,2024/25,Weichweizen,Berechnete Kennzahl,Importquote,%,35.44

Original rows: 1632
Added quota rows: 102
Extended dataset rows: 1734

In [140]:

# Check the calculated quota rows

# Number of results per product and quota
display(
    quota_results.groupby(
        ["Bilanz Produkt", "Bilanz Position"]
    ).size().unstack(fill_value=0)
)

# Show the first calculated values
display(
    quota_results[
        [
            "Wirtschaftsjahr",
            "Bilanz Produkt",
            "Bilanz Position",
            "Bilanz Einheit",
            "Bilanz Wert",
        ]
    ].head(20).round({"Bilanz Wert": 2})
)

# Check for missing values in the calculated ratios
print(
    "Missing quota values:",
    quota_results["Bilanz Wert"].isna().sum()
)

Bilanz Position  Exportquote  Importquote
Bilanz Produkt
Gerste                     0           34
Kartoffeln                34            0
Weichweizen                0           34

,Wirtschaftsjahr,Bilanz Produkt,Bilanz Position,Bilanz Einheit,Bilanz Wert
1632,1991/92,Gerste,Importquote,%,11.59
1633,1991/92,Kartoffeln,Exportquote,%,9.47
1634,1991/92,Weichweizen,Importquote,%,12.37
1635,1992/93,Gerste,Importquote,%,9.86
1636,1992/93,Kartoffeln,Exportquote,%,9.97
1637,1992/93,Weichweizen,Importquote,%,15.09
1638,1993/94,Gerste,Importquote,%,11.91
1639,1993/94,Kartoffeln,Exportquote,%,8.62
1640,1993/94,Weichweizen,Importquote,%,12.65
1641,1994/95,Gerste,Importquote,%,12.35
1642,1994/95,Kartoffeln,Exportquote,%,11.33
1643,1994/95,Weichweizen,Importquote,%,12.41
1644,1995/96,Gerste,Importquote,%,14.89
1645,1995/96,Kartoffeln,Exportquote,%,11.42
1646,1995/96,Weichweizen,Importquote,%,13.63
1647,1996/97,Gerste,Importquote,%,10.99
1648,1996/97,Kartoffeln,Exportquote,%,11.57
1649,1996/97,Weichweizen,Importquote,%,12.51
1650,1997/98,Gerste,Importquote,%,8.81
1651,1997/98,Kartoffeln,Exportquote,%,12.76

Missing quota values: 0

In [141]:

display(
    df[df["Bilanz Position"].isin([
        "Einfuhr",
        "Ausfuhr",
        "Inlandsverwendung insgesamt",
        "Gesamterzeugung",
    ])]
    .groupby(["Bilanz Produkt", "Bilanz Position"])
    .size()
    .unstack(fill_value=0)
)

Bilanz Position,Ausfuhr,Einfuhr,Gesamterzeugung,Inlandsverwendung insgesamt
Bilanz Produkt,,,,
Gerste,34,34,0,34
Kartoffeln,34,34,34,0
Weichweizen,34,34,0,34

In [142]:

display(
    df.loc[
        df["Bilanz Produkt"].isin(
            ["Gerste", "Kartoffeln", "Weichweizen"]
        ),
        ["Bilanz Produkt", "Bilanz Oberbegriff", "Bilanz Position"]
    ]
    .drop_duplicates()
    .sort_values(["Bilanz Produkt", "Bilanz Position"])
    .to_string(index=False)
)

'Bilanz Produkt    Bilanz Oberbegriff                                                    Bilanz Position\n        Gerste        Anfangsbestand                                                     Anfangsbestand\n        Gerste               Ausfuhr                                                            Ausfuhr\n        Gerste               Einfuhr                                                            Einfuhr\n        Gerste            Endbestand                                                         Endbestand\n        Gerste        Detailposition                                                             Futter\n        Gerste        Detailposition                                            Industrielle Verwertung\n        Gerste        Detailposition                                Industrielle Verwertung für Energie\n        Gerste        Detailposition                                        Inlandsverwendung insgesamt\n        Gerste        Detailposition                                    Nahrungsverbrauch Ausbeute in %\n        Gerste        Detailposition                                  Nahrungsverbrauch in Getreidewert\n        Gerste        Detailposition                    Nahrungsverbrauch in Getreidewert in kg je Kopf\n        Gerste             Verbrauch                                Nahrungsverbrauch in Produktgewicht\n        Gerste     Verbrauch je Kopf                  Nahrungsverbrauch in Produktgewicht in kg je Kopf\n        Gerste        Detailposition                                                            Saatgut\n        Gerste Selbstversorgungsgrad                                         Selbstversorgungsgrad in %\n        Gerste        Detailposition                                                           Verluste\n        Gerste            Produktion                                              Verwendbare Erzeugung\n    Kartoffeln               Ausfuhr                                                            Ausfuhr\n    Kartoffeln      Bestandsänderung                                                   Bestandsänderung\n    Kartoffeln               Einfuhr                                                            Einfuhr\n    Kartoffeln        Detailposition                                                             Futter\n    Kartoffeln       Gesamterzeugung                                                    Gesamterzeugung\n    Kartoffeln        Detailposition                                            Industrielle Verwertung\n    Kartoffeln        Detailposition                                                  Inlandsverwendung\n    Kartoffeln             Verbrauch                                                  Nahrungsverbrauch\n    Kartoffeln        Detailposition                             Nahrungsverbrauch Kartoffelerzeugnisse\n    Kartoffeln     Verbrauch je Kopf                                    Nahrungsverbrauch in kg je Kopf\n    Kartoffeln        Detailposition                                                            Saatgut\n    Kartoffeln Selbstversorgungsgrad                                         Selbstversorgungsgrad in %\n    Kartoffeln        Detailposition                                                           Verluste\n    Kartoffeln Verwendbare Erzeugung                                              Verwendbare Erzeugung\n   Weichweizen        Anfangsbestand                                                     Anfangsbestand\n   Weichweizen               Ausfuhr                                                            Ausfuhr\n   Weichweizen               Einfuhr                                                            Einfuhr\n   Weichweizen            Endbestand                                                         Endbestand\n   Weichweizen        Detailposition                                                             Futter\n   Weichweizen        Detailposition                                            Industrielle Verwertung\n   Weichweizen        Detailposition                               Industrielle Verwertung für  Energie\n   Weichweizen        Detailposition                                Industrielle Verwertung für Energie\n   Weichweizen        Detailposition                                        Inlandsverwendung insgesamt\n   Weichweizen        Detailposition                                    Nahrungsverbrauch Ausbeute in %\n   Weichweizen        Detailposition                                  Nahrungsverbrauch in Getreidewert\n   Weichweizen        Detailposition                    Nahrungsverbrauch in Getreidewert in kg je Kopf\n   Weichweizen             Verbrauch                                Nahrungsverbrauch in Produktgewicht\n   Weichweizen     Verbrauch je Kopf                  Nahrungsverbrauch in Produktgewicht in kg je Kopf\n   Weichweizen     Verbrauch je Kopf Nahrungsverbrauch in Produktgewicht in kg je Kopf/ dgl. kg je Kopf\n   Weichweizen             Verbrauch                   Nahrungsverbrauch in Produktgewicht/ in Mehlwert\n   Weichweizen        Detailposition                                                            Saatgut\n   Weichweizen Selbstversorgungsgrad                                         Selbstversorgungsgrad in %\n   Weichweizen        Detailposition                                                           Verluste\n   Weichweizen            Produktion                                              Verwendbare Erzeugung'

In [143]:

bilanzpositionen = sorted(
    df["Bilanz Position"].dropna().unique()
)

display(pd.DataFrame({
    "Bilanz Position": bilanzpositionen
}))

print("Anzahl eindeutiger Bilanzpositionen:", len(bilanzpositionen))

                                      Bilanz Position
0                                      Anfangsbestand
1                                             Ausfuhr
2                                    Bestandsänderung
3                                             Einfuhr
4                                          Endbestand
5                                              Futter
6                                     Gesamterzeugung
7                             Industrielle Verwertung
8                Industrielle Verwertung für  Energie
9                 Industrielle Verwertung für Energie
10                                  Inlandsverwendung
11                        Inlandsverwendung insgesamt
12                                  Nahrungsverbrauch
13                    Nahrungsverbrauch Ausbeute in %
14             Nahrungsverbrauch Kartoffelerzeugnisse
15                  Nahrungsverbrauch in Getreidewert
16    Nahrungsverbrauch in Getreidewert in kg je Kopf
17                Nahrungsverbrauch in Produktgewicht
18  Nahrungsverbrauch in Produktgewicht in kg je Kopf
19  Nahrungsverbrauch in Produktgewicht in kg je K...
20   Nahrungsverbrauch in Produktgewicht/ in Mehlwert
21                    Nahrungsverbrauch in kg je Kopf
22                                            Saatgut
23                         Selbstversorgungsgrad in %
24                                           Verluste
25                              Verwendbare Erzeugung

Anzahl eindeutiger Bilanzpositionen: 26

In [144]:

# Create a comparison table of selected balance sheet items by marketing year and product

vergleichspositionen = [
    "Inlandsverwendung",
    "Inlandsverwendung insgesamt",
    "Verwendbare Erzeugung",
    "Gesamterzeugung",
]

vergleich = df[
    df["Bilanz Position"].isin(vergleichspositionen)
].pivot_table(
    index=["Wirtschaftsjahr", "Bilanz Produkt"],
    columns="Bilanz Position",
    values="Bilanz Wert",
    aggfunc="first"
).reset_index()

display(
    vergleich.sort_values(
        ["Bilanz Produkt", "Wirtschaftsjahr"]
    ).round(2)
)

Bilanz Position,Wirtschaftsjahr,Bilanz Produkt,Gesamterzeugung,Inlandsverwendung,Inlandsverwendung insgesamt,Verwendbare Erzeugung
0,1991/92,Gerste,NaN,NaN,10637.00,14494.0
3,1992/93,Gerste,NaN,NaN,10502.00,12196.0
6,1993/94,Gerste,NaN,NaN,9692.00,11006.0
9,1994/95,Gerste,NaN,NaN,9901.00,10750.0
12,1995/96,Gerste,NaN,NaN,10523.00,11758.0
...,...,...,...,...,...,...
89,2020/21,Weichweizen,NaN,NaN,17592.75,21989.1
92,2021/22,Weichweizen,NaN,NaN,16999.75,21252.3
95,2022/23,Weichweizen,NaN,NaN,17059.07,22368.9
98,2023/24,Weichweizen,NaN,NaN,17980.67,21297.9
101,2024/25,Weichweizen,NaN,NaN,16889.56,18241.2

In [145]:
# Display and sort selected balance sheet items by product, marketing year, and position
vergleichspositionen = [
    "Inlandsverwendung",
    "Inlandsverwendung insgesamt",
    "Verwendbare Erzeugung",
    "Gesamterzeugung",
]

display(
    df.loc[
        df["Bilanz Position"].isin(vergleichspositionen),
        [
            "Wirtschaftsjahr",
            "Bilanz Produkt",
            "Bilanz Position",
            "Bilanz Einheit",
            "Bilanz Wert",
        ],
    ]
    .sort_values(
        ["Bilanz Produkt", "Wirtschaftsjahr", "Bilanz Position"]
    )
    .to_string(index=False)
)

'Wirtschaftsjahr Bilanz Produkt             Bilanz Position         Bilanz Einheit  Bilanz Wert\n        1991/92         Gerste Inlandsverwendung insgesamt 1 000 t Produktgewicht  10637.00000\n        1991/92         Gerste       Verwendbare Erzeugung 1 000 t Produktgewicht  14494.00000\n        1992/93         Gerste Inlandsverwendung insgesamt 1 000 t Produktgewicht  10502.00000\n        1992/93         Gerste       Verwendbare Erzeugung 1 000 t Produktgewicht  12196.00000\n        1993/94         Gerste Inlandsverwendung insgesamt 1 000 t Produktgewicht   9692.00000\n        1993/94         Gerste       Verwendbare Erzeugung 1 000 t Produktgewicht  11006.00000\n        1994/95         Gerste Inlandsverwendung insgesamt 1 000 t Produktgewicht   9901.00000\n        1994/95         Gerste       Verwendbare Erzeugung 1 000 t Produktgewicht  10750.00000\n        1995/96         Gerste Inlandsverwendung insgesamt 1 000 t Produktgewicht  10523.00000\n        1995/96         Gerste       Verwendbare Erzeugung 1 000 t Produktgewicht  11758.00000\n        1996/97         Gerste Inlandsverwendung insgesamt 1 000 t Produktgewicht   9971.00000\n        1996/97         Gerste       Verwendbare Erzeugung 1 000 t Produktgewicht  12074.00000\n        1997/98         Gerste Inlandsverwendung insgesamt 1 000 t Produktgewicht  10089.00000\n        1997/98         Gerste       Verwendbare Erzeugung 1 000 t Produktgewicht  13399.00000\n        1998/99         Gerste Inlandsverwendung insgesamt 1 000 t Produktgewicht  10163.00000\n        1998/99         Gerste       Verwendbare Erzeugung 1 000 t Produktgewicht  12474.00000\n        1999/00         Gerste Inlandsverwendung insgesamt 1 000 t Produktgewicht   9814.00000\n        1999/00         Gerste       Verwendbare Erzeugung 1 000 t Produktgewicht  13179.00000\n        2000/01         Gerste Inlandsverwendung insgesamt 1 000 t Produktgewicht  10004.00000\n        2000/01         Gerste       Verwendbare Erzeugung 1 000 t Produktgewicht  12089.00000\n        2001/02         Gerste Inlandsverwendung insgesamt 1 000 t Produktgewicht  10270.00000\n        2001/02         Gerste       Verwendbare Erzeugung 1 000 t Produktgewicht  13434.00000\n        2002/03         Gerste Inlandsverwendung insgesamt 1 000 t Produktgewicht   9928.00000\n        2002/03         Gerste       Verwendbare Erzeugung 1 000 t Produktgewicht  10906.00000\n        2003/04         Gerste Inlandsverwendung insgesamt 1 000 t Produktgewicht  10148.00000\n        2003/04         Gerste       Verwendbare Erzeugung 1 000 t Produktgewicht  10490.00000\n        2004/05         Gerste Inlandsverwendung insgesamt 1 000 t Produktgewicht  10128.00000\n        2004/05         Gerste       Verwendbare Erzeugung 1 000 t Produktgewicht  12966.00000\n        2005/06         Gerste Inlandsverwendung insgesamt 1 000 t Produktgewicht   9760.00000\n        2005/06         Gerste       Verwendbare Erzeugung 1 000 t Produktgewicht  11523.00000\n        2006/07         Gerste Inlandsverwendung insgesamt 1 000 t Produktgewicht  10815.54467\n        2006/07         Gerste       Verwendbare Erzeugung 1 000 t Produktgewicht  11966.55472\n        2007/08         Gerste Inlandsverwendung insgesamt 1 000 t Produktgewicht  10042.10903\n        2007/08         Gerste       Verwendbare Erzeugung 1 000 t Produktgewicht  10384.21790\n        2008/09         Gerste Inlandsverwendung insgesamt 1 000 t Produktgewicht  10319.04887\n        2008/09         Gerste       Verwendbare Erzeugung 1 000 t Produktgewicht  11956.61671\n        2009/10         Gerste Inlandsverwendung insgesamt 1 000 t Produktgewicht  10487.15374\n        2009/10         Gerste       Verwendbare Erzeugung 1 000 t Produktgewicht  12288.09998\n        2010/11         Gerste Inlandsverwendung insgesamt 1 000 t Produktgewicht  10450.71026\n        2010/11         Gerste       Verwendbare Erzeugung 1 000 t Produktgewicht  10263.50710\n        2011/12         Gerste Inlandsverwendung insgesamt 1 000 t Produktgewicht   8991.91387\n        2011/12         Gerste       Verwendbare Erzeugung 1 000 t Produktgewicht   8733.75980\n        2012/13         Gerste Inlandsverwendung insgesamt 1 000 t Produktgewicht   9306.99385\n        2012/13         Gerste       Verwendbare Erzeugung 1 000 t Produktgewicht  10391.31552\n        2013/14         Gerste Inlandsverwendung insgesamt 1 000 t Produktgewicht   9582.17349\n        2013/14         Gerste       Verwendbare Erzeugung 1 000 t Produktgewicht  10343.62698\n        2014/15         Gerste Inlandsverwendung insgesamt 1 000 t Produktgewicht   9752.83264\n        2014/15         Gerste       Verwendbare Erzeugung 1 000 t Produktgewicht  11562.80000\n        2015/16         Gerste Inlandsverwendung insgesamt 1 000 t Produktgewicht   9548.09460\n        2015/16         Gerste       Verwendbare Erzeugung 1 000 t Produktgewicht  11629.90000\n        2016/17         Gerste Inlandsverwendung insgesamt 1 000 t Produktgewicht   9591.73562\n        2016/17         Gerste       Verwendbare Erzeugung 1 000 t Produktgewicht  10730.50000\n        2017/18         Gerste Inlandsverwendung insgesamt 1 000 t Produktgewicht   9055.52887\n        2017/18         Gerste       Verwendbare Erzeugung 1 000 t Produktgewicht  10853.41410\n        2018/19         Gerste Inlandsverwendung insgesamt 1 000 t Produktgewicht   9213.57784\n        2018/19         Gerste       Verwendbare Erzeugung 1 000 t Produktgewicht   9583.56988\n        2019/20         Gerste Inlandsverwendung insgesamt 1 000 t Produktgewicht   9990.85453\n        2019/20         Gerste       Verwendbare Erzeugung 1 000 t Produktgewicht  11591.50000\n        2020/21         Gerste Inlandsverwendung insgesamt 1 000 t Produktgewicht   9506.68352\n        2020/21         Gerste       Verwendbare Erzeugung 1 000 t Produktgewicht  10769.20000\n        2021/22         Gerste Inlandsverwendung insgesamt 1 000 t Produktgewicht   7886.53224\n        2021/22         Gerste       Verwendbare Erzeugung 1 000 t Produktgewicht  10411.10000\n        2022/23         Gerste Inlandsverwendung insgesamt 1 000 t Produktgewicht   8653.54489\n        2022/23         Gerste       Verwendbare Erzeugung 1 000 t Produktgewicht  11207.10000\n        2023/24         Gerste Inlandsverwendung insgesamt 1 000 t Produktgewicht   8269.04381\n        2023/24         Gerste       Verwendbare Erzeugung 1 000 t Produktgewicht  10999.90000\n        2024/25         Gerste Inlandsverwendung insgesamt 1 000 t Produktgewicht   8540.49858\n        2024/25         Gerste       Verwendbare Erzeugung 1 000 t Produktgewicht  10610.00000\n        1991/92     Kartoffeln             Gesamterzeugung 1 000 t Produktgewicht  10584.00000\n        1991/92     Kartoffeln           Inlandsverwendung 1 000 t Produktgewicht  10787.00000\n        1991/92     Kartoffeln       Verwendbare Erzeugung 1 000 t Produktgewicht   9737.00000\n        1992/93     Kartoffeln             Gesamterzeugung 1 000 t Produktgewicht  11258.00000\n        1992/93     Kartoffeln           Inlandsverwendung 1 000 t Produktgewicht  10644.00000\n        1992/93     Kartoffeln       Verwendbare Erzeugung 1 000 t Produktgewicht  10358.00000\n        1993/94     Kartoffeln             Gesamterzeugung 1 000 t Produktgewicht  12645.00000\n        1993/94     Kartoffeln           Inlandsverwendung 1 000 t Produktgewicht  11912.00000\n        1993/94     Kartoffeln       Verwendbare Erzeugung 1 000 t Produktgewicht  11633.00000\n        1994/95     Kartoffeln             Gesamterzeugung 1 000 t Produktgewicht  10636.00000\n        1994/95     Kartoffeln           Inlandsverwendung 1 000 t Produktgewicht  10218.00000\n        1994/95     Kartoffeln       Verwendbare Erzeugung 1 000 t Produktgewicht   9785.00000\n        1995/96     Kartoffeln             Gesamterzeugung 1 000 t Produktgewicht  10888.00000\n        1995/96     Kartoffeln           Inlandsverwendung 1 000 t Produktgewicht  10458.00000\n        1995/96     Kartoffeln       Verwendbare Erzeugung 1 000 t Produktgewicht  10017.00000\n        1996/97     Kartoffeln             Gesamterzeugung 1 000 t Produktgewicht  13558.00000\n        1996/97     Kartoffeln           Inlandsverwendung 1 000 t Produktgewicht  12223.00000\n        1996/97     Kartoffeln       Verwendbare Erzeugung 1 000 t Produktgewicht  12473.00000\n        1997/98     Kartoffeln             Gesamterzeugung 1 000 t Produktgewicht  12067.00000\n        1997/98     Kartoffeln           Inlandsverwendung 1 000 t Produktgewicht  11226.00000\n        1997/98     Kartoffeln       Verwendbare Erzeugung 1 000 t Produktgewicht  11102.00000\n        1998/99     Kartoffeln             Gesamterzeugung 1 000 t Produktgewicht  11712.00000\n        1998/99     Kartoffeln           Inlandsverwendung 1 000 t Produktgewicht  10670.00000\n        1998/99     Kartoffeln       Verwendbare Erzeugung 1 000 t Produktgewicht  10775.00000\n        1999/00     Kartoffeln             Gesamterzeugung 1 000 t Produktgewicht  12031.00000\n        1999/00     Kartoffeln           Inlandsverwendung 1 000 t Produktgewicht  10690.00000\n        1999/00     Kartoffeln       Verwendbare Erzeugung 1 000 t Produktgewicht  11069.00000\n        2000/01     Kartoffeln             Gesamterzeugung 1 000 t Produktgewicht  13694.00000\n        2000/01     Kartoffeln           Inlandsverwendung 1 000 t Produktgewicht  11835.00000\n        2000/01     Kartoffeln       Verwendbare Erzeugung 1 000 t Produktgewicht  12598.00000\n        2001/02     Kartoffeln             Gesamterzeugung 1 000 t Produktgewicht  11917.00000\n        2001/02     Kartoffeln           Inlandsverwendung 1 000 t Produktgewicht  10186.00000\n        2001/02     Kartoffeln       Verwendbare Erzeugung 1 000 t Produktgewicht  10964.00000\n        2002/03     Kartoffeln             Gesamterzeugung 1 000 t Produktgewicht  11492.00000\n        2002/03     Kartoffeln           Inlandsverwendung 1 000 t Produktgewicht   9888.00000\n        2002/03     Kartoffeln       Verwendbare Erzeugung 1 000 t Produktgewicht  10573.00000\n        2003/04     Kartoffeln             Gesamterzeugung 1 000 t Produktgewicht  10232.00000\n        2003/04     Kartoffeln           Inlandsverwendung 1 000 t Produktgewicht   8706.00000\n        2003/04     Kartoffeln       Verwendbare Erzeugung 1 000 t Produktgewicht   9413.00000\n        2004/05     Kartoffeln             Gesamterzeugung 1 000 t Produktgewicht  13043.60000\n        2004/05     Kartoffeln           Inlandsverwendung 1 000 t Produktgewicht  11292.55576\n        2004/05     Kartoffeln       Verwendbare Erzeugung 1 000 t Produktgewicht  12360.11536\n        2005/06     Kartoffeln             Gesamterzeugung 1 000 t Produktgewicht  11624.00000\n        2005/06     Kartoffeln           Inlandsverwendung 1 000 t Produktgewicht   8186.99778\n        2005/06     Kartoffeln       Verwendbare Erzeugung 1 000 t Produktgewicht  10993.73908\n        2006/07     Kartoffeln             Gesamterzeugung 1 000 t Produktgewicht  10291.00000\n        2006/07     Kartoffeln           Inlandsverwendung 1 000 t Produktgewicht   7574.21225\n        2006/07     Kartoffeln       Verwendbare Erzeugung 1 000 t Produktgewicht   9468.09276\n        2007/08     Kartoffeln             Gesamterzeugung 1 000 t Produktgewicht  11923.00000\n        2007/08     Kartoffeln           Inlandsverwendung 1 000 t Produktgewicht   8129.55211\n        2007/08     Kartoffeln       Verwendbare Erzeugung 1 000 t Produktgewicht  10969.36083\n        2008/09     Kartoffeln             Gesamterzeugung 1 000 t Produktgewicht  11619.00000\n        2008/09     Kartoffeln           Inlandsverwendung 1 000 t Produktgewicht   7912.00000\n        2008/09     Kartoffeln       Verwendbare Erzeugung 1 000 t Produktgewicht  10690.00000\n        2009/10     Kartoffeln             Gesamterzeugung 1 000 t Produktgewicht  11917.00000\n        2009/10     Kartoffeln           Inlandsverwendung 1 000 t Produktgewicht   8037.81427\n        2009/10     Kartoffeln       Verwendbare Erzeugung 1 000 t Produktgewicht  10963.40622\n        2010/11     Kartoffeln             Gesamterzeugung 1 000 t Produktgewicht  10143.00000\n        2010/11     Kartoffeln           Inlandsverwendung 1 000 t Produktgewicht   6905.46770\n        2010/11     Kartoffeln       Verwendbare Erzeugung 1 000 t Produktgewicht   9555.60223\n        2011/12     Kartoffeln             Gesamterzeugung 1 000 t Produktgewicht  12098.00000\n        2011/12     Kartoffeln           Inlandsverwendung 1 000 t Produktgewicht   7432.00000\n        2011/12     Kartoffeln       Verwendbare Erzeugung 1 000 t Produktgewicht  11130.00000\n        2012/13     Kartoffeln             Gesamterzeugung 1 000 t Produktgewicht  10666.00000\n        2012/13     Kartoffeln           Inlandsverwendung 1 000 t Produktgewicht   6838.96472\n        2012/13     Kartoffeln       Verwendbare Erzeugung 1 000 t Produktgewicht  10028.21152\n        2013/14     Kartoffeln             Gesamterzeugung 1 000 t Produktgewicht   9670.00000\n        2013/14     Kartoffeln           Inlandsverwendung 1 000 t Produktgewicht   6454.00000\n        2013/14     Kartoffeln       Verwendbare Erzeugung 1 000 t Produktgewicht   9092.00000\n        2014/15     Kartoffeln             Gesamterzeugung 1 000 t Produktgewicht  11607.00000\n        2014/15     Kartoffeln           Inlandsverwendung 1 000 t Produktgewicht   7010.00000\n        2014/15     Kartoffeln       Verwendbare Erzeugung 1 000 t Produktgewicht  10795.00000\n        2015/16     Kartoffeln             Gesamterzeugung 1 000 t Produktgewicht  10370.00000\n        2015/16     Kartoffeln           Inlandsverwendung 1 000 t Produktgewicht   6573.00000\n        2015/16     Kartoffeln       Verwendbare Erzeugung 1 000 t Produktgewicht   9644.00000\n        2016/17     Kartoffeln             Gesamterzeugung 1 000 t Produktgewicht  10772.00000\n        2016/17     Kartoffeln           Inlandsverwendung 1 000 t Produktgewicht   6498.00000\n        2016/17     Kartoffeln       Verwendbare Erzeugung 1 000 t Produktgewicht   9869.00000\n        2017/18     Kartoffeln             Gesamterzeugung 1 000 t Produktgewicht  11720.00000\n        2017/18     Kartoffeln           Inlandsverwendung 1 000 t Produktgewicht   7084.00000\n        2017/18     Kartoffeln       Verwendbare Erzeugung 1 000 t Produktgewicht  10499.00000\n        2018/19     Kartoffeln             Gesamterzeugung 1 000 t Produktgewicht   8921.00000\n        2018/19     Kartoffeln           Inlandsverwendung 1 000 t Produktgewicht   6342.00000\n        2018/19     Kartoffeln       Verwendbare Erzeugung 1 000 t Produktgewicht   8778.00000\n        2019/20     Kartoffeln             Gesamterzeugung 1 000 t Produktgewicht  10602.00000\n        2019/20     Kartoffeln           Inlandsverwendung 1 000 t Produktgewicht   6774.00000\n        2019/20     Kartoffeln       Verwendbare Erzeugung 1 000 t Produktgewicht   9752.00000\n        2020/21     Kartoffeln             Gesamterzeugung 1 000 t Produktgewicht  11715.10000\n        2020/21     Kartoffeln           Inlandsverwendung 1 000 t Produktgewicht   7437.40000\n        2020/21     Kartoffeln       Verwendbare Erzeugung 1 000 t Produktgewicht  10655.80000\n        2021/22     Kartoffeln             Gesamterzeugung 1 000 t Produktgewicht  11312.10000\n        2021/22     Kartoffeln           Inlandsverwendung 1 000 t Produktgewicht   6951.60000\n        2021/22     Kartoffeln       Verwendbare Erzeugung 1 000 t Produktgewicht  10404.90000\n        2022/23     Kartoffeln             Gesamterzeugung 1 000 t Produktgewicht  10683.40000\n        2022/23     Kartoffeln           Inlandsverwendung 1 000 t Produktgewicht   6253.74502\n        2022/23     Kartoffeln       Verwendbare Erzeugung 1 000 t Produktgewicht   9826.60000\n        2023/24     Kartoffeln             Gesamterzeugung 1 000 t Produktgewicht  11607.30000\n        2023/24     Kartoffeln           Inlandsverwendung 1 000 t Produktgewicht   7205.70000\n        2023/24     Kartoffeln       Verwendbare Erzeugung 1 000 t Produktgewicht  10676.40000\n        2024/25     Kartoffeln             Gesamterzeugung 1 000 t Produktgewicht  12703.30000\n        2024/25     Kartoffeln           Inlandsverwendung 1 000 t Produktgewicht   7873.70000\n        2024/25     Kartoffeln       Verwendbare Erzeugung 1 000 t Produktgewicht  11424.80000\n        1991/92    Weichweizen Inlandsverwendung insgesamt 1 000 t Produktgewicht  11639.00000\n        1991/92    Weichweizen       Verwendbare Erzeugung 1 000 t Produktgewicht  16531.00000\n        1992/93    Weichweizen Inlandsverwendung insgesamt 1 000 t Produktgewicht  11004.00000\n        1992/93    Weichweizen       Verwendbare Erzeugung 1 000 t Produktgewicht  15472.00000\n        1993/94    Weichweizen Inlandsverwendung insgesamt 1 000 t Produktgewicht  12943.00000\n        1993/94    Weichweizen       Verwendbare Erzeugung 1 000 t Produktgewicht  15720.00000\n        1994/95    Weichweizen Inlandsverwendung insgesamt 1 000 t Produktgewicht  14470.00000\n        1994/95    Weichweizen       Verwendbare Erzeugung 1 000 t Produktgewicht  16177.00000\n        1995/96    Weichweizen Inlandsverwendung insgesamt 1 000 t Produktgewicht  14705.00000\n        1995/96    Weichweizen       Verwendbare Erzeugung 1 000 t Produktgewicht  17361.00000\n        1996/97    Weichweizen Inlandsverwendung insgesamt 1 000 t Produktgewicht  14101.00000\n        1996/97    Weichweizen       Verwendbare Erzeugung 1 000 t Produktgewicht  18875.00000\n        1997/98    Weichweizen Inlandsverwendung insgesamt 1 000 t Produktgewicht  14297.00000\n        1997/98    Weichweizen       Verwendbare Erzeugung 1 000 t Produktgewicht  19588.00000\n        1998/99    Weichweizen Inlandsverwendung insgesamt 1 000 t Produktgewicht  15285.00000\n        1998/99    Weichweizen       Verwendbare Erzeugung 1 000 t Produktgewicht  19896.00000\n        1999/00    Weichweizen Inlandsverwendung insgesamt 1 000 t Produktgewicht  13593.00000\n        1999/00    Weichweizen       Verwendbare Erzeugung 1 000 t Produktgewicht  19258.00000\n        2000/01    Weichweizen Inlandsverwendung insgesamt 1 000 t Produktgewicht  15475.00000\n        2000/01    Weichweizen       Verwendbare Erzeugung 1 000 t Produktgewicht  21553.00000\n        2001/02    Weichweizen Inlandsverwendung insgesamt 1 000 t Produktgewicht  15818.00000\n        2001/02    Weichweizen       Verwendbare Erzeugung 1 000 t Produktgewicht  22708.00000\n        2002/03    Weichweizen Inlandsverwendung insgesamt 1 000 t Produktgewicht  16407.00000\n        2002/03    Weichweizen       Verwendbare Erzeugung 1 000 t Produktgewicht  20720.00000\n        2003/04    Weichweizen Inlandsverwendung insgesamt 1 000 t Produktgewicht  14753.00000\n        2003/04    Weichweizen       Verwendbare Erzeugung 1 000 t Produktgewicht  18895.00000\n        2004/05    Weichweizen Inlandsverwendung insgesamt 1 000 t Produktgewicht  16230.00000\n        2004/05    Weichweizen       Verwendbare Erzeugung 1 000 t Produktgewicht  25289.00000\n        2005/06    Weichweizen Inlandsverwendung insgesamt 1 000 t Produktgewicht  19634.00000\n        2005/06    Weichweizen       Verwendbare Erzeugung 1 000 t Produktgewicht  23642.00000\n        2006/07    Weichweizen Inlandsverwendung insgesamt 1 000 t Produktgewicht  18855.70554\n        2006/07    Weichweizen       Verwendbare Erzeugung 1 000 t Produktgewicht  22365.91981\n        2007/08    Weichweizen Inlandsverwendung insgesamt 1 000 t Produktgewicht  17106.67274\n        2007/08    Weichweizen       Verwendbare Erzeugung 1 000 t Produktgewicht  20790.11036\n        2008/09    Weichweizen Inlandsverwendung insgesamt 1 000 t Produktgewicht  18544.06585\n        2008/09    Weichweizen       Verwendbare Erzeugung 1 000 t Produktgewicht  25881.55494\n        2009/10    Weichweizen Inlandsverwendung insgesamt 1 000 t Produktgewicht  17030.71519\n        2009/10    Weichweizen 

In [146]:

# Overview of the relevant balance sheet items
relevante_positionen = [
    "Einfuhr",
    "Ausfuhr",
    "Inlandsverwendung",
    "Inlandsverwendung insgesamt",
    "Gesamterzeugung",
    "Verwendbare Erzeugung",
    "Selbstversorgungsgrad in %",
]

positions_check = (
    df.loc[
        df["Bilanz Position"].isin(relevante_positionen),
        [
            "Bilanz Produkt",
            "Bilanz Position",
            "Bilanz Einheit",
        ],
    ]
    .drop_duplicates()
    .sort_values(["Bilanz Produkt", "Bilanz Position"])
)

display(positions_check)

     Bilanz Produkt              Bilanz Position          Bilanz Einheit
13           Gerste                      Ausfuhr  1 000 t Produktgewicht
11           Gerste                      Einfuhr  1 000 t Produktgewicht
0            Gerste  Inlandsverwendung insgesamt  1 000 t Produktgewicht
9            Gerste   Selbstversorgungsgrad in %                      %
15           Gerste        Verwendbare Erzeugung  1 000 t Produktgewicht
588      Kartoffeln                      Ausfuhr  1 000 t Produktgewicht
585      Kartoffeln                      Einfuhr  1 000 t Produktgewicht
591      Kartoffeln              Gesamterzeugung  1 000 t Produktgewicht
581      Kartoffeln            Inlandsverwendung  1 000 t Produktgewicht
584      Kartoffeln   Selbstversorgungsgrad in %                      %
590      Kartoffeln        Verwendbare Erzeugung  1 000 t Produktgewicht
1067    Weichweizen                      Ausfuhr  1 000 t Produktgewicht
1065    Weichweizen                      Einfuhr  1 000 t Produktgewicht
1054    Weichweizen  Inlandsverwendung insgesamt  1 000 t Produktgewicht
1063    Weichweizen   Selbstversorgungsgrad in %                      %
1069    Weichweizen        Verwendbare Erzeugung  1 000 t Produktgewicht

### Methodological Note: Bilanz Position Comparability

Before calculating import and export ratios, the availability of relevant balance positions was checked across barley, potatoes, and soft wheat.

| Balance Position | Barley | Potatoes | Soft Wheat |
|---|---|---|---|
| Imports | ✓ | ✓ | ✓ |
| Exports | ✓ | ✓ | ✓ |
| Domestic Use | Total | Available | Total |
| Total Production | — | ✓ | — |
| Usable Production | ✓ | ✓ | ✓ |
| Self-sufficiency Rate | ✓ | ✓ | ✓ |

**Methodological decision:** Usable production is available for all three products and will be assessed as a common denominator for the export ratio. For the import ratio, the domestic-use positions must first be confirmed as comparable using official BLE definitions. The original BLE self-sufficiency rates will be retained unchanged.

All calculated ratios will be stored separately to preserve the original dataset.

In [147]:

# Select the required balance sheet items for the ratios
positions = [
    "Einfuhr",
    "Ausfuhr",
    "Inlandsverwendung",
    "Inlandsverwendung insgesamt",
    "Verwendbare Erzeugung",
]

quota_input = df.loc[
    df["Bilanz Position"].isin(positions),
    [
        "Wirtschaftsjahr",
        "Bilanz Produkt",
        "Bilanz Position",
        "Bilanz Wert",
    ],
].copy()

display(quota_input.head(10))

print("Zeilen:", len(quota_input))
print("Produkte:", quota_input["Bilanz Produkt"].unique())

   Wirtschaftsjahr Bilanz Produkt              Bilanz Position  Bilanz Wert
0          1991/92         Gerste  Inlandsverwendung insgesamt      10637.0
11         1991/92         Gerste                      Einfuhr       1233.0
13         1991/92         Gerste                      Ausfuhr       3537.0
15         1991/92         Gerste        Verwendbare Erzeugung      14494.0
17         1992/93         Gerste  Inlandsverwendung insgesamt      10502.0
28         1992/93         Gerste                      Einfuhr       1035.0
30         1992/93         Gerste                      Ausfuhr       2725.0
32         1992/93         Gerste        Verwendbare Erzeugung      12196.0
34         1993/94         Gerste  Inlandsverwendung insgesamt       9692.0
45         1993/94         Gerste                      Einfuhr       1154.0

Zeilen: 408
Produkte: <StringArray>
['Gerste', 'Kartoffeln', 'Weichweizen']
Length: 3, dtype: str

In [148]:

# Check whether each combination is unique
duplicate_rows = quota_input[
    quota_input.duplicated(
        subset=[
            "Wirtschaftsjahr",
            "Bilanz Produkt",
            "Bilanz Position",
        ],
        keep=False,
    )
]

print("Number of duplicate combinations:", len(duplicate_rows))

# Count available years for each product and balance position
position_counts = (
    quota_input
    .groupby(["Bilanz Produkt", "Bilanz Position"])["Wirtschaftsjahr"]
    .nunique()
    .unstack(fill_value=0)
)

display(position_counts)

Number of duplicate combinations: 0

Bilanz Position,Ausfuhr,Einfuhr,Inlandsverwendung,Inlandsverwendung insgesamt,Verwendbare Erzeugung
Bilanz Produkt,,,,,
Gerste,34,34,0,34,34
Kartoffeln,34,34,34,0,34
Weichweizen,34,34,0,34,34

### Methodology: Import and Export Ratios

Before calculating the ratios, the availability and uniqueness of the relevant balance positions were checked for all three products across 34 financial years. No duplicate combinations were found.

**Calculation rules**

- **Import Ratio (%)** = Imports / Domestic Use × 100
- **Export Ratio (%)** = Exports / Usable Production × 100

The domestic-use position differs by product: `Inlandsverwendung insgesamt` is used for barley and soft wheat, while `Inlandsverwendung` is used for potatoes.

`Verwendbare Erzeugung` is selected as the common denominator for the export ratio because it is available for all three products. `Gesamterzeugung`, available only for potatoes, is excluded to maintain consistency pending confirmation of the official definitions.

The ratios are self-calculated analytical indicators, not official BLE indicators. The original dataset and published self-sufficiency rates remain unchanged.

In [149]:

# Define the relevant balance positions for each product
domestic_use_positions = {
    "Gerste": "Inlandsverwendung insgesamt",
    "Kartoffeln": "Inlandsverwendung",
    "Weichweizen": "Inlandsverwendung insgesamt",
}

# Select the required balance positions
required_positions = [
    "Einfuhr",
    "Ausfuhr",
    "Inlandsverwendung",
    "Inlandsverwendung insgesamt",
    "Verwendbare Erzeugung",
]

quota_input = df.loc[
    df["Bilanz Position"].isin(required_positions)
].copy()

# Prepare the data for calculation
quota_rows = []

for product, domestic_use_position in domestic_use_positions.items():
    product_data = quota_input[
        quota_input["Bilanz Produkt"] == product
    ]

    for year in product_data["Wirtschaftsjahr"].unique():
        year_data = product_data[
            product_data["Wirtschaftsjahr"] == year
        ]

        values = year_data.set_index("Bilanz Position")["Bilanz Wert"]

        # Retrieve the required values
        imports = values.get("Einfuhr")
        exports = values.get("Ausfuhr")
        domestic_use = values.get(domestic_use_position)
        usable_production = values.get("Verwendbare Erzeugung")

        # Skip calculations if required values are missing
        if (
            imports is None
            or exports is None
            or domestic_use is None
            or usable_production is None
            or domestic_use == 0
            or usable_production == 0
        ):
            continue

        # Calculate import and export ratios
        import_ratio = imports / domestic_use * 100
        export_ratio = exports / usable_production * 100

        # Store the calculated ratios as new rows
        for position, value in [
            ("Importquote", import_ratio),
            ("Exportquote", export_ratio),
        ]:
            quota_rows.append({
                "Wirtschaftsjahr": year,
                "Bilanz Produkt": product,
                "Bilanz Oberbegriff": "Abgeleitete Kennzahl",
                "Bilanz Position": position,
                "Bilanz Einheit": "%",
                "Bilanz Wert": value,
            })

# Create a separate DataFrame containing the calculated ratios
quota_results = pd.DataFrame(quota_rows)

# Append the new rows without modifying the original dataset
df_extended = pd.concat(
    [df, quota_results],
    ignore_index=True
)

# Display the results
display(quota_results.head(10))

print("Calculated ratio rows:", len(quota_results))
print("Original dataset shape:", df.shape)
print("Extended dataset shape:", df_extended.shape)

,Wirtschaftsjahr,Bilanz Produkt,Bilanz Oberbegriff,Bilanz Position,Bilanz Einheit,Bilanz Wert
0,1991/92,Gerste,Abgeleitete Kennzahl,Importquote,%,11.591614
1,1991/92,Gerste,Abgeleitete Kennzahl,Exportquote,%,24.403201
2,1992/93,Gerste,Abgeleitete Kennzahl,Importquote,%,9.855266
3,1992/93,Gerste,Abgeleitete Kennzahl,Exportquote,%,22.343391
4,1993/94,Gerste,Abgeleitete Kennzahl,Importquote,%,11.906727
5,1993/94,Gerste,Abgeleitete Kennzahl,Exportquote,%,30.119935
6,1994/95,Gerste,Abgeleitete Kennzahl,Importquote,%,12.352288
7,1994/95,Gerste,Abgeleitete Kennzahl,Exportquote,%,30.241860
8,1995/96,Gerste,Abgeleitete Kennzahl,Importquote,%,14.891191
9,1995/96,Gerste,Abgeleitete Kennzahl,Exportquote,%,31.467937

Calculated ratio rows: 204
Original dataset shape: (1632, 6)
Extended dataset shape: (1836, 6)

In [150]:
# Check decimal places in the original self-sufficiency rates
self_sufficiency = df.loc[
    df["Bilanz Position"] == "Selbstversorgungsgrad in %",
    ["Bilanz Produkt", "Bilanz Wert"]
]

display(self_sufficiency.head(10))

print("Decimal places in the original values:")
display(self_sufficiency["Bilanz Wert"].map(
    lambda x: len(str(x).split(".")[-1]) if "." in str(x) else 0
).value_counts().sort_index())

    Bilanz Produkt  Bilanz Wert
9           Gerste    136.26022
26          Gerste    116.13026
43          Gerste    113.55757
60          Gerste    108.57489
77          Gerste    111.73620
94          Gerste    121.09116
111         Gerste    132.80801
128         Gerste    122.73935
145         Gerste    134.28775
162         Gerste    120.84166

Decimal places in the original values:

Bilanz Wert
1    14
4     8
5    80
Name: count, dtype: int64

In [151]:

# Check the number of calculated ratios by product and ratio type
ratio_check = quota_results.groupby(
    ["Bilanz Produkt", "Bilanz Position"]
).size().unstack(fill_value=0)

display(ratio_check)

# Check the total number of calculated ratios per product
print("\nTotal ratio rows per product:")
display(quota_results.groupby("Bilanz Produkt").size())

Bilanz Position  Exportquote  Importquote
Bilanz Produkt
Gerste                    34           34
Kartoffeln                34           34
Weichweizen               34           34

Total ratio rows per product:

Bilanz Produkt
Gerste         68
Kartoffeln     68
Weichweizen    68
dtype: int64

In [152]:
# Plausability Check
# Check the minimum and maximum values of the calculated ratios
ratio_plausibility = quota_results.groupby(
    ["Bilanz Produkt", "Bilanz Position"]
)["Bilanz Wert"].agg(["min", "max", "mean"])

display(ratio_plausibility.round(2))

                                  min    max   mean
Bilanz Produkt Bilanz Position
Gerste         Exportquote      11.50  48.43  28.35
               Importquote       8.81  23.65  15.17
Kartoffeln     Exportquote       9.37  62.31  36.24
               Importquote      11.08  40.78  23.21
Weichweizen    Exportquote      26.68  53.23  39.63
               Importquote       8.46  39.05  20.93

In [153]:

# Inspect the original balance values for the first financial year
# used in the ratio calculations

display(
    df.loc[
        (df["Wirtschaftsjahr"] == "1991/92")
        & (df["Bilanz Produkt"].isin(
            ["Gerste", "Kartoffeln", "Weichweizen"]
        ))
        & (df["Bilanz Position"].isin([
            "Einfuhr",
            "Ausfuhr",
            "Inlandsverwendung",
            "Inlandsverwendung insgesamt",
            "Verwendbare Erzeugung",
        ])),
        [
            "Wirtschaftsjahr",
            "Bilanz Produkt",
            "Bilanz Position",
            "Bilanz Einheit",
            "Bilanz Wert",
        ],
    ].sort_values(["Bilanz Produkt", "Bilanz Position"])
)

,Wirtschaftsjahr,Bilanz Produkt,Bilanz Position,Bilanz Einheit,Bilanz Wert
13,1991/92,Gerste,Ausfuhr,1 000 t Produktgewicht,3537.0
11,1991/92,Gerste,Einfuhr,1 000 t Produktgewicht,1233.0
0,1991/92,Gerste,Inlandsverwendung insgesamt,1 000 t Produktgewicht,10637.0
15,1991/92,Gerste,Verwendbare Erzeugung,1 000 t Produktgewicht,14494.0
588,1991/92,Kartoffeln,Ausfuhr,1 000 t Produktgewicht,1002.0
585,1991/92,Kartoffeln,Einfuhr,1 000 t Produktgewicht,1757.0
581,1991/92,Kartoffeln,Inlandsverwendung,1 000 t Produktgewicht,10787.0
590,1991/92,Kartoffeln,Verwendbare Erzeugung,1 000 t Produktgewicht,9737.0
1067,1991/92,Weichweizen,Ausfuhr,1 000 t Produktgewicht,4941.0
1065,1991/92,Weichweizen,Einfuhr,1 000 t Produktgewicht,1440.0
1054,1991/92,Weichweizen,Inlandsverwendung insgesamt,1 000 t Produktgewicht,11639.0
1069,1991/92,Weichweizen,Verwendbare Erzeugung,1 000 t Produktgewicht,16531.0

In [154]:

# Display the calculated ratios for 1991/92
display(
    quota_results.loc[
        quota_results["Wirtschaftsjahr"].eq("1991/92"),
        [
            "Wirtschaftsjahr",
            "Bilanz Produkt",
            "Bilanz Position",
            "Bilanz Wert",
        ],
    ].sort_values(["Bilanz Produkt", "Bilanz Position"])
)

    Wirtschaftsjahr Bilanz Produkt Bilanz Position  Bilanz Wert
1           1991/92         Gerste     Exportquote    24.403201
0           1991/92         Gerste     Importquote    11.591614
69          1991/92     Kartoffeln     Exportquote    10.290644
68          1991/92     Kartoffeln     Importquote    16.288125
137         1991/92    Weichweizen     Exportquote    29.889299
136         1991/92    Weichweizen     Importquote    12.372197

In [155]:

# Save the extended dataset with the calculated import and export ratios

output_path = project_dir / "data" / "processed" / "ble_cleaned_supply_balance_with_quotas_1991-2025.xlsx"

df_extended.to_excel(output_path, index=False)

print("File saved to:", output_path)
print("Saved dataset shape:", df_extended.shape)

File saved to: c:\Users\incog\Desktop\Portfolio_Project_Agriculture\data\processed\ble_cleaned_supply_balance_with_quotas_1991-2025.xlsx
Saved dataset shape: (1836, 6)

In [156]:

# Load the processed dataset with calculated import and export ratios

input_path = (
    project_dir
    / "data"
    / "processed"
    / "ble_cleaned_supply_balance_with_quotas_1991-2025.xlsx"
)

df_analysis = pd.read_excel(input_path)

print("Loaded file:", input_path.name)
print("Dataset shape:", df_analysis.shape)

display(df_analysis.head())

Loaded file: ble_cleaned_supply_balance_with_quotas_1991-2025.xlsx
Dataset shape: (1836, 6)

,Wirtschaftsjahr,Bilanz Produkt,Bilanz Oberbegriff,Bilanz Position,Bilanz Einheit,Bilanz Wert
0,1991/92,Gerste,Detailposition,Inlandsverwendung insgesamt,1 000 t Produktgewicht,10637.0
1,1991/92,Gerste,Detailposition,Nahrungsverbrauch in Getreidewert,1 000 t Getreidewert,10.0
2,1991/92,Gerste,Detailposition,Industrielle Verwertung für Energie,1 000 t Produktgewicht,NaN
3,1991/92,Gerste,Detailposition,Saatgut,1 000 t Produktgewicht,388.0
4,1991/92,Gerste,Detailposition,Industrielle Verwertung,1 000 t Produktgewicht,2671.0

### Data Validation - Import and Export Records

Before calculating the net trade balance, the completeness of the import and export records is checked for barley, potatoes and soft wheat.

For each product and financial year, the import and export quantities must be available and expressed in comparable units. Missing values and duplicate records will be checked before the calculation.

The original dataset remains unchanged.

In [157]:

# Check import and export records for completeness and duplicates

trade_positions = df_analysis.loc[
    df_analysis["Bilanz Position"].isin(["Einfuhr", "Ausfuhr"]),
    [
        "Wirtschaftsjahr",
        "Bilanz Produkt",
        "Bilanz Position",
        "Bilanz Einheit",
        "Bilanz Wert",
    ],
].copy()

# Count records and non-missing values
trade_check = trade_positions.groupby(
    ["Bilanz Produkt", "Bilanz Position"]
).agg(
    total_rows=("Bilanz Wert", "size"),
    non_missing_values=("Bilanz Wert", "count"),
)

display(trade_check)

# Check for duplicate product-year-position combinations
duplicate_count = trade_positions.duplicated(
    subset=[
        "Wirtschaftsjahr",
        "Bilanz Produkt",
        "Bilanz Position",
    ]
).sum()

print("Duplicate records:", duplicate_count)

                                total_rows  non_missing_values
Bilanz Produkt Bilanz Position
Gerste         Ausfuhr                  34                  34
               Einfuhr                  34                  34
Kartoffeln     Ausfuhr                  34                  34
               Einfuhr                  34                  34
Weichweizen    Ausfuhr                  34                  34
               Einfuhr                  34                  34

Duplicate records: 0

### Net Trade Balance

The net trade balance is calculated as exports minus imports for each product and financial year.

**Formula:**

Net Trade Balance = Exports − Imports

A positive value indicates that exports exceed imports, while a negative value indicates that imports exceed exports.

The indicator is measured in 1,000 tonnes of product weight. The calculation is performed in a separate DataFrame, leaving the processed dataset unchanged.

In [158]:

import pandas as pd

# Select import and export records
trade_data = df.loc[
    df["Bilanz Position"].isin(["Einfuhr", "Ausfuhr"]),
    [
        "Wirtschaftsjahr",
        "Bilanz Produkt",
        "Bilanz Einheit",
        "Bilanz Position",
        "Bilanz Wert",
    ],
].copy()

# Reshape imports and exports temporarily for calculation
trade_wide = trade_data.pivot_table(
    index=["Wirtschaftsjahr", "Bilanz Produkt", "Bilanz Einheit"],
    columns="Bilanz Position",
    values="Bilanz Wert",
    aggfunc="first",
).reset_index()

# Calculate net trade balance
trade_wide["Bilanz Wert"] = (
    trade_wide["Ausfuhr"] - trade_wide["Einfuhr"]
)

# Create new rows using the original six-column structure
new_rows = pd.DataFrame({
    "Wirtschaftsjahr": trade_wide["Wirtschaftsjahr"],
    "Bilanz Produkt": trade_wide["Bilanz Produkt"],
    "Bilanz Oberbegriff": "Kennzahlen",
    "Bilanz Position": "Nettohandelsbilanz",
    "Bilanz Einheit": trade_wide["Bilanz Einheit"],
    "Bilanz Wert": trade_wide["Bilanz Wert"],
})

# Append the new rows while keeping the original six columns
df_mit_kennzahlen = pd.concat(
    [df, new_rows],
    ignore_index=True,
)

# Check the result
print("Original number of columns:", len(df.columns))
print("Number of columns after adding indicators:", len(df_mit_kennzahlen.columns))
print("Original number of rows:", len(df))
print("Number of rows after adding indicators:", len(df_mit_kennzahlen))

display(
    df_mit_kennzahlen[
        df_mit_kennzahlen["Bilanz Position"] == "Nettohandelsbilanz"
    ].head(10)
)

Original number of columns: 6
Number of columns after adding indicators: 6
Original number of rows: 1632
Number of rows after adding indicators: 1734

,Wirtschaftsjahr,Bilanz Produkt,Bilanz Oberbegriff,Bilanz Position,Bilanz Einheit,Bilanz Wert
1632,1991/92,Gerste,Kennzahlen,Nettohandelsbilanz,1 000 t Produktgewicht,2304.0
1633,1991/92,Kartoffeln,Kennzahlen,Nettohandelsbilanz,1 000 t Produktgewicht,-755.0
1634,1991/92,Weichweizen,Kennzahlen,Nettohandelsbilanz,1 000 t Produktgewicht,3501.0
1635,1992/93,Gerste,Kennzahlen,Nettohandelsbilanz,1 000 t Produktgewicht,1690.0
1636,1992/93,Kartoffeln,Kennzahlen,Nettohandelsbilanz,1 000 t Produktgewicht,-336.0
1637,1992/93,Weichweizen,Kennzahlen,Nettohandelsbilanz,1 000 t Produktgewicht,3797.0
1638,1993/94,Gerste,Kennzahlen,Nettohandelsbilanz,1 000 t Produktgewicht,2161.0
1639,1993/94,Kartoffeln,Kennzahlen,Nettohandelsbilanz,1 000 t Produktgewicht,-230.0
1640,1993/94,Weichweizen,Kennzahlen,Nettohandelsbilanz,1 000 t Produktgewicht,6165.0
1641,1994/95,Gerste,Kennzahlen,Nettohandelsbilanz,1 000 t Produktgewicht,2028.0

In [159]:
### Zusatz von 15.10.2026

import pandas as pd

# Select import and export records
trade_data = df_analysis.loc[
    df_analysis["Bilanz Position"].isin(["Einfuhr", "Ausfuhr"]),
    [
        "Wirtschaftsjahr",
        "Bilanz Produkt",
        "Bilanz Einheit",
        "Bilanz Position",
        "Bilanz Wert",
    ],
].copy()

# Reshape imports and exports temporarily for calculation
trade_wide = trade_data.pivot_table(
    index=["Wirtschaftsjahr", "Bilanz Produkt", "Bilanz Einheit"],
    columns="Bilanz Position",
    values="Bilanz Wert",
    aggfunc="first",
).reset_index()

# Calculate net trade balance
trade_wide["Bilanz Wert"] = (
    trade_wide["Ausfuhr"] - trade_wide["Einfuhr"]
)

# Convert the calculated results back into the original six-column structure
new_rows = pd.DataFrame({
    "Wirtschaftsjahr": trade_wide["Wirtschaftsjahr"],
    "Bilanz Produkt": trade_wide["Bilanz Produkt"],
    "Bilanz Oberbegriff": "Kennzahlen",
    "Bilanz Position": "Nettohandelsbilanz",
    "Bilanz Einheit": trade_wide["Bilanz Einheit"],
    "Bilanz Wert": trade_wide["Bilanz Wert"],
})

# Append the new rows without changing the original DataFrame
df_with_indicators = pd.concat(
    [df_analysis, new_rows],
    ignore_index=True,
)

# Display the result
display(df_with_indicators.tail(10))

print("Original number of columns:", len(df_analysis.columns))
print("Number of columns after adding indicators:", len(df_with_indicators.columns))

,Wirtschaftsjahr,Bilanz Produkt,Bilanz Oberbegriff,Bilanz Position,Bilanz Einheit,Bilanz Wert
1928,2021/22,Weichweizen,Kennzahlen,Nettohandelsbilanz,1 000 t Produktgewicht,3641.26543
1929,2022/23,Gerste,Kennzahlen,Nettohandelsbilanz,1 000 t Produktgewicht,2624.24024
1930,2022/23,Kartoffeln,Kennzahlen,Nettohandelsbilanz,1 000 t Produktgewicht,3572.84630
1931,2022/23,Weichweizen,Kennzahlen,Nettohandelsbilanz,1 000 t Produktgewicht,3834.07991
1932,2023/24,Gerste,Kennzahlen,Nettohandelsbilanz,1 000 t Produktgewicht,2438.03405
1933,2023/24,Kartoffeln,Kennzahlen,Nettohandelsbilanz,1 000 t Produktgewicht,3470.70000
1934,2023/24,Weichweizen,Kennzahlen,Nettohandelsbilanz,1 000 t Produktgewicht,3303.10470
1935,2024/25,Gerste,Kennzahlen,Nettohandelsbilanz,1 000 t Produktgewicht,2289.05471
1936,2024/25,Kartoffeln,Kennzahlen,Nettohandelsbilanz,1 000 t Produktgewicht,3551.10000
1937,2024/25,Weichweizen,Kennzahlen,Nettohandelsbilanz,1 000 t Produktgewicht,2801.76137

Original number of columns: 6
Number of columns after adding indicators: 6

In [160]:

# Validate the calculated net trade balance

print("Total records:", len(net_trade_balance))
print(
    "Missing net trade balance values:",
    net_trade_balance["Nettohandelsbilanz"].isna().sum()
)

# Summarize the balance by product
net_trade_summary = net_trade_balance.groupby(
    "Bilanz Produkt"
)["Nettohandelsbilanz"].agg(
    minimum="min",
    maximum="max",
    mean="mean",
    positive_years=lambda values: (values > 0).sum(),
    negative_years=lambda values: (values < 0).sum(),
)

display(net_trade_summary.round(2))

Total records: 102
Missing net trade balance values: 0

                minimum  maximum     mean  positive_years  negative_years
Bilanz Produkt
Gerste           187.74  5404.00  1769.04              34               0
Kartoffeln      -755.00  3572.85  1896.33              29               5
Weichweizen     2801.76  8267.74  5030.53              34               0

In [161]:
# Check usable production records for completeness and duplicates

production_check = df_analysis.loc[
    df_analysis["Bilanz Position"] == "Verwendbare Erzeugung",
    [
        "Wirtschaftsjahr",
        "Bilanz Produkt",
        "Bilanz Einheit",
        "Bilanz Wert",
    ],
].copy()

# Summarize records and non-missing values by product
production_summary = production_check.groupby(
    "Bilanz Produkt"
).agg(
    total_rows=("Bilanz Wert", "size"),
    non_missing_values=("Bilanz Wert", "count"),
    unique_years=("Wirtschaftsjahr", "nunique"),
)

display(production_summary)

# Check duplicate product-year combinations
production_duplicates = production_check.duplicated(
    subset=["Wirtschaftsjahr", "Bilanz Produkt"]
).sum()

print("Duplicate product-year records:", production_duplicates)

# Check units for each product
print("\nUnits found:")
display(
    production_check.groupby(
        ["Bilanz Produkt", "Bilanz Einheit"]
    ).size().rename("record_count")
)

                total_rows  non_missing_values  unique_years
Bilanz Produkt
Gerste                  34                  34            34
Kartoffeln              34                  34            34
Weichweizen             34                  34            34

Duplicate product-year records: 0

Units found:

Bilanz Produkt  Bilanz Einheit
Gerste          1 000 t Produktgewicht    34
Kartoffeln      1 000 t Produktgewicht    34
Weichweizen     1 000 t Produktgewicht    34
Name: record_count, dtype: int64

#### Calculate Year-over-Year Change in Usable Production

The year-over-year percentage change is calculated separately for barley, potatoes and soft wheat. The percentage change compares each financial year's usable production with the previous financial year's value.

The first financial year has no previous-year comparison and is therefore assigned a missing value. The calculation is performed in a separate DataFrame, leaving the original dataset unchanged.

In [162]:
# Calculate year-over-year changes in usable production

# Sort records by product and financial year
production_change = production_check.sort_values(
    ["Bilanz Produkt", "Wirtschaftsjahr"]
).copy()

# Calculate the previous year's usable production
production_change["Vorjahr"] = (
    production_change.groupby("Bilanz Produkt")["Bilanz Wert"]
    .shift(1)
)

# Calculate the percentage change compared with the previous year
production_change["Veränderung in %"] = (
    (
        production_change["Bilanz Wert"]
        - production_change["Vorjahr"]
    )
    / production_change["Vorjahr"]
    * 100
)

# Select the columns needed for the analysis
production_change = production_change[
    [
        "Wirtschaftsjahr",
        "Bilanz Produkt",
        "Bilanz Wert",
        "Vorjahr",
        "Veränderung in %",
    ]
].copy()

display(production_change.head(10))

print("Total records:", len(production_change))
print(
    "Missing year-over-year changes:",
    production_change["Veränderung in %"].isna().sum()
)

    Wirtschaftsjahr Bilanz Produkt  Bilanz Wert  Vorjahr  Veränderung in %
15          1991/92         Gerste      14494.0      NaN               NaN
32          1992/93         Gerste      12196.0  14494.0        -15.854836
49          1993/94         Gerste      11006.0  12196.0         -9.757297
66          1994/95         Gerste      10750.0  11006.0         -2.326004
83          1995/96         Gerste      11758.0  10750.0          9.376744
100         1996/97         Gerste      12074.0  11758.0          2.687532
117         1997/98         Gerste      13399.0  12074.0         10.973994
134         1998/99         Gerste      12474.0  13399.0         -6.903500
151         1999/00         Gerste      13179.0  12474.0          5.651756
168         2000/01         Gerste      12089.0  13179.0         -8.270734

Total records: 102
Missing year-over-year changes: 3

In [163]:
# Validate year-over-year changes in usable production

# Summarize the year-over-year changes by product
production_change_validation = production_change.groupby(
    "Bilanz Produkt"
).agg(
    total_rows=("Veränderung in %", "size"),
    missing_changes=(
        "Veränderung in %",
        lambda values: values.isna().sum()
    ),
    minimum_change=("Veränderung in %", "min"),
    maximum_change=("Veränderung in %", "max"),
)

display(production_change_validation.round(2))

# Count missing changes across all products
print(
    "Total missing year-over-year changes:",
    production_change["Veränderung in %"].isna().sum()
)

# Count missing changes for each product
print("\nMissing changes by product:")
display(
    production_change.groupby("Bilanz Produkt")[
        "Veränderung in %"
    ].apply(lambda values: values.isna().sum())
)

                total_rows  missing_changes  minimum_change  maximum_change
Bilanz Produkt
Gerste                  34                1          -18.82           23.60
Kartoffeln              34                1          -16.39           31.31
Weichweizen             34                1          -17.22           33.84

Total missing year-over-year changes: 3

Missing changes by product:

Bilanz Produkt
Gerste         1
Kartoffeln     1
Weichweizen    1
Name: Veränderung in %, dtype: int64

In [164]:
# Summarize year-over-year changes by product

production_change_summary = production_change.groupby(
    "Bilanz Produkt"
)["Veränderung in %"].agg(
    minimum_change="min",
    maximum_change="max",
    mean_change="mean",
    mean_absolute_change=lambda values: values.abs().mean(),
)

display(production_change_summary.round(2))

,minimum_change,maximum_change,mean_change,mean_absolute_change
Bilanz Produkt,,,,
Gerste,-18.82,23.60,-0.33,9.20
Kartoffeln,-16.39,31.31,1.21,10.41
Weichweizen,-17.22,33.84,0.80,7.88

### Year-over-Year Change in Domestic Use

The year-over-year percentage change in domestic use measures how the domestic use of barley, potatoes and soft wheat changes compared with the previous financial year.

For barley and soft wheat, the balance item "Inlandsverwendung insgesamt" is used. For potatoes, the balance item "Inlandsverwendung" is used, following the previously established methodology.

Changes in domestic use can help contextualize developments in import ratios and self-sufficiency rates. However, this indicator alone does not explain the causes of changes in domestic use.

The first financial year has no year-over-year comparison. The original dataset remains unchanged.

In [165]:
# Check domestic use records for completeness and duplicates

domestic_use_positions = {
    "Gerste": "Inlandsverwendung insgesamt",
    "Kartoffeln": "Inlandsverwendung",
    "Weichweizen": "Inlandsverwendung insgesamt",
}

domestic_use_check = df_analysis.loc[
    df_analysis.apply(
        lambda row: domestic_use_positions.get(row["Bilanz Produkt"])
        == row["Bilanz Position"],
        axis=1,
    ),
    [
        "Wirtschaftsjahr",
        "Bilanz Produkt",
        "Bilanz Position",
        "Bilanz Einheit",
        "Bilanz Wert",
    ],
].copy()

# Summarize records and non-missing values by product
domestic_use_summary = domestic_use_check.groupby(
    "Bilanz Produkt"
).agg(
    total_rows=("Bilanz Wert", "size"),
    non_missing_values=("Bilanz Wert", "count"),
    unique_years=("Wirtschaftsjahr", "nunique"),
)

display(domestic_use_summary)

# Check duplicate product-year combinations
domestic_use_duplicates = domestic_use_check.duplicated(
    subset=["Wirtschaftsjahr", "Bilanz Produkt"]
).sum()

print("Duplicate product-year records:", domestic_use_duplicates)

# Check units used for domestic use
print("\nUnits found:")
display(
    domestic_use_check.groupby(
        ["Bilanz Produkt", "Bilanz Einheit"]
    ).size().rename("record_count")
)

                total_rows  non_missing_values  unique_years
Bilanz Produkt
Gerste                  34                  34            34
Kartoffeln              34                  34            34
Weichweizen             34                  34            34

Duplicate product-year records: 0

Units found:

Bilanz Produkt  Bilanz Einheit
Gerste          1 000 t Produktgewicht    34
Kartoffeln      1 000 t Produktgewicht    34
Weichweizen     1 000 t Produktgewicht    34
Name: record_count, dtype: int64

In [166]:
# Calculate year-over-year changes in domestic use

# Sort records by product and financial year
domestic_use_change = domestic_use_check.sort_values(
    ["Bilanz Produkt", "Wirtschaftsjahr"]
).copy()

# Calculate the previous year's domestic use
domestic_use_change["Vorjahr"] = (
    domestic_use_change.groupby("Bilanz Produkt")["Bilanz Wert"]
    .shift(1)
)

# Calculate the percentage change compared with the previous year
domestic_use_change["Veränderung in %"] = (
    (
        domestic_use_change["Bilanz Wert"]
        - domestic_use_change["Vorjahr"]
    )
    / domestic_use_change["Vorjahr"]
    * 100
)

# Keep the columns needed for the analysis
domestic_use_change = domestic_use_change[
    [
        "Wirtschaftsjahr",
        "Bilanz Produkt",
        "Bilanz Wert",
        "Vorjahr",
        "Veränderung in %",
    ]
].copy()

# Display the first records
display(domestic_use_change.head(10))

# Check the total number of records and missing changes
print("Total records:", len(domestic_use_change))
print(
    "Missing year-over-year changes:",
    domestic_use_change["Veränderung in %"].isna().sum()
)

    Wirtschaftsjahr Bilanz Produkt  Bilanz Wert  Vorjahr  Veränderung in %
0           1991/92         Gerste      10637.0      NaN               NaN
17          1992/93         Gerste      10502.0  10637.0         -1.269155
34          1993/94         Gerste       9692.0  10502.0         -7.712817
51          1994/95         Gerste       9901.0   9692.0          2.156418
68          1995/96         Gerste      10523.0   9901.0          6.282194
85          1996/97         Gerste       9971.0  10523.0         -5.245652
102         1997/98         Gerste      10089.0   9971.0          1.183432
119         1998/99         Gerste      10163.0  10089.0          0.733472
136         1999/00         Gerste       9814.0  10163.0         -3.434025
153         2000/01         Gerste      10004.0   9814.0          1.936010

Total records: 102
Missing year-over-year changes: 3

In [167]:
# Validate year-over-year changes in domestic use

# Summarize the calculated changes by product
domestic_use_change_validation = domestic_use_change.groupby(
    "Bilanz Produkt"
).agg(
    total_rows=("Veränderung in %", "size"),
    missing_changes=(
        "Veränderung in %",
        lambda values: values.isna().sum()
    ),
    minimum_change=("Veränderung in %", "min"),
    maximum_change=("Veränderung in %", "max"),
)

display(domestic_use_change_validation.round(2))

# Check the total number of records
print("Total records:", len(domestic_use_change))

# Check missing changes across all products
print(
    "Total missing year-over-year changes:",
    domestic_use_change["Veränderung in %"].isna().sum()
)

# Check missing changes by product
print("\nMissing changes by product:")
display(
    domestic_use_change.groupby("Bilanz Produkt")[
        "Veränderung in %"
    ].apply(lambda values: values.isna().sum())
)

                total_rows  missing_changes  minimum_change  maximum_change
Bilanz Produkt
Gerste                  34                1          -17.04           10.82
Kartoffeln              34                1          -27.50           29.71
Weichweizen             34                1          -12.54           20.97

Total records: 102
Total missing year-over-year changes: 3

Missing changes by product:

Bilanz Produkt
Gerste         1
Kartoffeln     1
Weichweizen    1
Name: Veränderung in %, dtype: int64

In [168]:
# Summarize year-over-year changes in domestic use

domestic_use_change_summary = domestic_use_change.groupby(
    "Bilanz Produkt"
)["Veränderung in %"].agg(
    minimum_change="min",
    maximum_change="max",
    mean_change="mean",
    mean_absolute_change=lambda values: values.abs().mean(),
)

display(domestic_use_change_summary.round(2))

,minimum_change,maximum_change,mean_change,mean_absolute_change
Bilanz Produkt,,,,
Gerste,-17.04,10.82,-0.49,4.38
Kartoffeln,-27.50,29.71,-0.31,9.22
Weichweizen,-12.54,20.97,1.47,6.76

In [169]:
# Save the current dataset

from pathlib import Path

project_dir = Path.cwd().parent

output_path = (
    project_dir
    / "data"
    / "processed"
    / "ble_cleaned_supply_balance_with_quotas_1991-2025.xlsx"
)

df_analysis.to_excel(output_path, index=False)

print("File saved:", output_path.name)
print("Dataset shape:", df_analysis.shape)

File saved: ble_cleaned_supply_balance_with_quotas_1991-2025.xlsx
Dataset shape: (1836, 6)

### Save Derived Indicators

This section saves the validated derived indicators as separate files. These files will be used to prepare the consolidated analytical dataset in the next notebook.

In [170]:
# Recalculate the net trade balance

trade_positions = df_analysis.loc[
    df_analysis["Bilanz Position"].isin(["Einfuhr", "Ausfuhr"]),
    [
        "Wirtschaftsjahr",
        "Bilanz Produkt",
        "Bilanz Position",
        "Bilanz Wert",
    ],
].copy()

trade_wide = trade_positions.pivot(
    index=["Wirtschaftsjahr", "Bilanz Produkt"],
    columns="Bilanz Position",
    values="Bilanz Wert",
).reset_index()

trade_wide.columns.name = None

net_trade_balance = trade_wide.copy()

net_trade_balance["Nettohandelsbilanz"] = (
    net_trade_balance["Ausfuhr"] - net_trade_balance["Einfuhr"]
)

print("Net trade balance recalculated.")
print("Dataset shape:", net_trade_balance.shape)

Net trade balance recalculated.
Dataset shape: (102, 5)

In [171]:
# Check which derived DataFrames are currently available

dataframe_names = [
    "df_analysis",
    "net_trade_balance",
    "production_change",
    "domestic_use_change",
]

for name in dataframe_names:
    if name in globals():
        print(f"{name}: available")
    else:
        print(f"{name}: not available")

df_analysis: available
net_trade_balance: available
production_change: available
domestic_use_change: available

In [172]:

# Save validated derived indicators

from pathlib import Path

project_dir = Path.cwd().parent
processed_dir = project_dir / "data" / "processed"
processed_dir.mkdir(parents=True, exist_ok=True)

# Save the net trade balance
net_trade_balance.to_excel(
    processed_dir / "ble_net_trade_balance_1991-2025.xlsx",
    index=False,
)

# Save year-over-year changes in usable production
production_change.to_excel(
    processed_dir / "ble_production_change_1991-2025.xlsx",
    index=False,
)

# Save year-over-year changes in domestic use
domestic_use_change.to_excel(
    processed_dir / "ble_domestic_use_change_1991-2025.xlsx",
    index=False,
)

print("Derived indicators saved successfully.")
print("Net trade balance:", net_trade_balance.shape)
print("Production changes:", production_change.shape)
print("Domestic use changes:", domestic_use_change.shape)

Derived indicators saved successfully.
Net trade balance: (102, 5)
Production changes: (102, 5)
Domestic use changes: (102, 5)