In [7]:

# Import libraries
from pathlib import Path

import pandas as pd

In [8]:

# Define project directory
project_dir = Path.cwd().parent

# Define source file path
file_path = (
    project_dir
    / "data"
    / "raw"
    / "bmelh_ble_versorgungsbilanzen_1990-2025_weichweizen_gerste_kartoffel"
    / "ble_versorgungsbilanzen_1991-2025"
    / "01_ready_to_clean_ble_supply_balance_all_products_1991-2025.xls"
)

# Check whether the source file exists
print(f"Project directory: {project_dir}")
print(f"Source file exists: {file_path.exists()}")
print(f"Source file path: {file_path}")

Project directory: c:\Users\incog\Desktop\Portfolio_Project_Agriculture
Source file exists: True
Source file path: c:\Users\incog\Desktop\Portfolio_Project_Agriculture\data\raw\bmelh_ble_versorgungsbilanzen_1990-2025_weichweizen_gerste_kartoffel\ble_versorgungsbilanzen_1991-2025\01_ready_to_clean_ble_supply_balance_all_products_1991-2025.xls

In [9]:

# Load source data
df = pd.read_excel(file_path, engine="xlrd")

# Display the first five rows
display(df.head())

,Wirtschaftsjahr,Bilanz Produkt,Bilanz Oberbegriff,Bilanz Position,Bilanz Einheit,Bilanz Wert
0,1991/92,Gerste,Detailposition,Inlandsverwendung insgesamt,1 000 t Produktgewicht,10637.0
1,1991/92,Gerste,Detailposition,Nahrungsverbrauch in Getreidewert,1 000 t Getreidewert,10.0
2,1991/92,Gerste,Detailposition,Industrielle Verwertung für Energie,1 000 t Produktgewicht,NaN
3,1991/92,Gerste,Detailposition,Saatgut,1 000 t Produktgewicht,388.0
4,1991/92,Gerste,Detailposition,Industrielle Verwertung,1 000 t Produktgewicht,2671.0

In [11]:

# Inspect dataset dimensions
print(f"Number of rows: {df.shape[0]}")
print(f"Number of columns: {df.shape[1]}")

# Inspect column names
print("\nColumn names:")
print(df.columns.tolist())

# Inspect data types and non-null values
print("\nDataset information:")
df.info()

Number of rows: 1646
Number of columns: 6

Column names:
['Wirtschaftsjahr', 'Bilanz Produkt', 'Bilanz Oberbegriff', 'Bilanz Position', 'Bilanz Einheit', 'Bilanz Wert']

Dataset information:
<class 'pandas.DataFrame'>
RangeIndex: 1646 entries, 0 to 1645
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Wirtschaftsjahr     1646 non-null   str
 1   Bilanz Produkt      1646 non-null   str
 2   Bilanz Oberbegriff  1646 non-null   str
 3   Bilanz Position     1646 non-null   str
 4   Bilanz Einheit      1646 non-null   str
 5   Bilanz Wert         1582 non-null   float64
dtypes: float64(1), str(5)
memory usage: 77.3 KB

In [12]:

# Display the first ten rows
display(df.head(10))

,Wirtschaftsjahr,Bilanz Produkt,Bilanz Oberbegriff,Bilanz Position,Bilanz Einheit,Bilanz Wert
0,1991/92,Gerste,Detailposition,Inlandsverwendung insgesamt,1 000 t Produktgewicht,10637.00000
1,1991/92,Gerste,Detailposition,Nahrungsverbrauch in Getreidewert,1 000 t Getreidewert,10.00000
2,1991/92,Gerste,Detailposition,Industrielle Verwertung für Energie,1 000 t Produktgewicht,NaN
3,1991/92,Gerste,Detailposition,Saatgut,1 000 t Produktgewicht,388.00000
4,1991/92,Gerste,Detailposition,Industrielle Verwertung,1 000 t Produktgewicht,2671.00000
5,1991/92,Gerste,Detailposition,Verluste,1 000 t Produktgewicht,351.00000
6,1991/92,Gerste,Detailposition,Nahrungsverbrauch Ausbeute in %,%,80.00000
7,1991/92,Gerste,Detailposition,Futter,1 000 t Produktgewicht,7217.00000
8,1991/92,Gerste,Detailposition,Nahrungsverbrauch in Getreidewert in kg je Kopf,1 000 t Getreidewert,NaN
9,1991/92,Gerste,Selbstversorgungsgrad,Selbstversorgungsgrad in %,%,136.26022

In [13]:

# Check missing values
print("Missing values per column:")
display(df.isna().sum().to_frame(name="Missing values"))

# Check duplicate rows
duplicate_count = df.duplicated().sum()
print(f"\nNumber of duplicate rows: {duplicate_count}")

# Check unique values per column
print("\nNumber of unique values per column:")
display(df.nunique().to_frame(name="Unique values"))

Missing values per column:

                    Missing values
Wirtschaftsjahr                  0
Bilanz Produkt                   0
Bilanz Oberbegriff               0
Bilanz Position                  0
Bilanz Einheit                   0
Bilanz Wert                     64

Number of duplicate rows: 0

Number of unique values per column:

                    Unique values
Wirtschaftsjahr                35
Bilanz Produkt                  3
Bilanz Oberbegriff             12
Bilanz Position                26
Bilanz Einheit                  8
Bilanz Wert                  1420

In [14]:

# Inspect rows with missing balance values
missing_values = (
    df.loc[
        df["Bilanz Wert"].isna(),
        [
            "Wirtschaftsjahr",
            "Bilanz Produkt",
            "Bilanz Oberbegriff",
            "Bilanz Position",
            "Bilanz Einheit",
        ],
    ]
    .sort_values(
        ["Bilanz Produkt", "Bilanz Position", "Wirtschaftsjahr"]
    )
)

# Display all rows with missing values
display(missing_values)

,Wirtschaftsjahr,Bilanz Produkt,Bilanz Oberbegriff,Bilanz Position,Bilanz Einheit
2,1991/92,Gerste,Detailposition,Industrielle Verwertung für Energie,1 000 t Produktgewicht
19,1992/93,Gerste,Detailposition,Industrielle Verwertung für Energie,1 000 t Produktgewicht
36,1993/94,Gerste,Detailposition,Industrielle Verwertung für Energie,1 000 t Produktgewicht
53,1994/95,Gerste,Detailposition,Industrielle Verwertung für Energie,1 000 t Produktgewicht
70,1995/96,Gerste,Detailposition,Industrielle Verwertung für Energie,1 000 t Produktgewicht
...,...,...,...,...,...
1246,2001/02,Weichweizen,Detailposition,Nahrungsverbrauch in Getreidewert in kg je Kopf,Kilogramm Getreidewert
1263,2002/03,Weichweizen,Detailposition,Nahrungsverbrauch in Getreidewert in kg je Kopf,Kilogramm Getreidewert
1280,2003/04,Weichweizen,Detailposition,Nahrungsverbrauch in Getreidewert in kg je Kopf,Kilogramm Getreidewert
1297,2004/05,Weichweizen,Detailposition,Nahrungsverbrauch in Getreidewert in kg je Kopf,Kilogramm Getreidewert
1314,2005/06,Weichweizen,Detailposition,Nahrungsverbrauch in Getreidewert in kg je Kopf,Kilogramm Getreidewert

In [15]:

# Summarize missing values by product and balance position
missing_summary = (
    df.loc[df["Bilanz Wert"].isna()]
    .groupby(
        [
            "Bilanz Produkt",
            "Bilanz Oberbegriff",
            "Bilanz Position",
            "Bilanz Einheit",
        ],
        dropna=False,
    )
    .size()
    .reset_index(name="Missing values")
    .sort_values(
        ["Bilanz Produkt", "Bilanz Position"]
    )
)

display(missing_summary)

,Bilanz Produkt,Bilanz Oberbegriff,Bilanz Position,Bilanz Einheit,Missing values
0,Gerste,Detailposition,Industrielle Verwertung für Energie,1 000 t Produktgewicht,15
1,Gerste,Detailposition,Nahrungsverbrauch in Getreidewert in kg je Kopf,1 000 t Getreidewert,15
2,Kartoffeln,Bestandsänderung,Bestandsänderung,1 000 t Produktgewicht,4
3,Weichweizen,Detailposition,Industrielle Verwertung für Energie,1 000 t Produktgewicht,15
4,Weichweizen,Detailposition,Nahrungsverbrauch in Getreidewert in kg je Kopf,Kilogramm Getreidewert,15

In [16]:

# Count missing values by product, balance position, and year
missing_by_year = (
    df.loc[df["Bilanz Wert"].isna()]
    .groupby(
        [
            "Bilanz Produkt",
            "Bilanz Position",
            "Wirtschaftsjahr",
        ],
        dropna=False,
    )
    .size()
    .reset_index(name="Missing values")
    .sort_values(
        [
            "Bilanz Produkt",
            "Bilanz Position",
            "Wirtschaftsjahr",
        ]
    )
)

display(missing_by_year)

,Bilanz Produkt,Bilanz Position,Wirtschaftsjahr,Missing values
0,Gerste,Industrielle Verwertung für Energie,1991/92,1
1,Gerste,Industrielle Verwertung für Energie,1992/93,1
2,Gerste,Industrielle Verwertung für Energie,1993/94,1
3,Gerste,Industrielle Verwertung für Energie,1994/95,1
4,Gerste,Industrielle Verwertung für Energie,1995/96,1
...,...,...,...,...
59,Weichweizen,Nahrungsverbrauch in Getreidewert in kg je Kopf,2001/02,1
60,Weichweizen,Nahrungsverbrauch in Getreidewert in kg je Kopf,2002/03,1
61,Weichweizen,Nahrungsverbrauch in Getreidewert in kg je Kopf,2003/04,1
62,Weichweizen,Nahrungsverbrauch in Getreidewert in kg je Kopf,2004/05,1
63,Weichweizen,Nahrungsverbrauch in Getreidewert in kg je Kopf,2005/06,1

In [18]:

# Summarize missing year ranges by product and balance position
missing_year_ranges = (
    df.loc[df["Bilanz Wert"].isna()]
    .groupby(
        ["Bilanz Produkt", "Bilanz Position"],
        dropna=False,
    )
    .agg(
        first_missing_year=("Wirtschaftsjahr", "min"),
        last_missing_year=("Wirtschaftsjahr", "max"),
        number_of_missing_years=("Wirtschaftsjahr", "nunique"),
    )
    .reset_index()
)

display(missing_year_ranges)

,Bilanz Produkt,Bilanz Position,first_missing_year,last_missing_year,number_of_missing_years
0,Gerste,Industrielle Verwertung für Energie,1991/92,2005/06,15
1,Gerste,Nahrungsverbrauch in Getreidewert in kg je Kopf,1991/92,2005/06,15
2,Kartoffeln,Bestandsänderung,2018/19,2021/22,4
3,Weichweizen,Industrielle Verwertung für Energie,1991/92,2005/06,15
4,Weichweizen,Nahrungsverbrauch in Getreidewert in kg je Kopf,1991/92,2005/06,15

In [19]:

# Count records by product
product_counts = (
    df.groupby("Bilanz Produkt")
    .size()
    .reset_index(name="Number of records")
    .sort_values("Bilanz Produkt")
)

display(product_counts)

# Check whether all products have the same number of records
same_record_count = product_counts["Number of records"].nunique() == 1

print(f"All products have the same number of records: {same_record_count}")

  Bilanz Produkt  Number of records
0         Gerste                578
1     Kartoffeln                490
2    Weichweizen                578

All products have the same number of records: False

In [30]:
# Data quality note: The combined dataset contains 1,646 records: 578 for barley, 490 for potatoes, and 578 for soft wheat. The differences in record counts were checked against the original source data and were confirmed to exist in the raw data. Therefore, the differences were not caused by the data consolidation process. Missing values are retained for further investigation rather than being automatically replaced or removed.

In [31]:
duplicate_count = df.duplicated().sum()
print(f"Number of duplicate rows: {duplicate_count}")

Number of duplicate rows: 0

In [32]:
# Check year coverage by product
year_coverage = (
    df.groupby("Bilanz Produkt")
    .agg(
        Number_of_records=("Wirtschaftsjahr", "size"),
        Unique_years=("Wirtschaftsjahr", "nunique"),
        First_year=("Wirtschaftsjahr", "min"),
        Last_year=("Wirtschaftsjahr", "max"),
    )
    .reset_index()
)

display(year_coverage)

  Bilanz Produkt  Number_of_records  Unique_years First_year Last_year
0         Gerste                578            34    1991/92   2024/25
1     Kartoffeln                490            35    1990/91   2024/25
2    Weichweizen                578            34    1991/92   2024/25

In [36]:
# Remove financial year 1990/91
df = df[df["Wirtschaftsjahr"] != "1990/91"].copy()

In [39]:
# Check year coverage by product
year_coverage = (
    df.groupby("Bilanz Produkt")
    .agg(
        Number_of_records=("Wirtschaftsjahr", "size"),
        Unique_years=("Wirtschaftsjahr", "nunique"),
        First_year=("Wirtschaftsjahr", "min"),
        Last_year=("Wirtschaftsjahr", "max"),
    )
    .reset_index()
)

display(year_coverage)

  Bilanz Produkt  Number_of_records  Unique_years First_year Last_year
0         Gerste                578            34    1991/92   2024/25
1     Kartoffeln                476            34    1991/92   2024/25
2    Weichweizen                578            34    1991/92   2024/25

In [42]:
# Check the dataset dimensions
print(df.shape)

(1632, 6)

In [40]:
# Count records per product and financial year
records_per_year = (
    df.groupby(["Wirtschaftsjahr", "Bilanz Produkt"])
    .size()
    .unstack(fill_value=0)
    .sort_index()
)

display(records_per_year)

Bilanz Produkt   Gerste  Kartoffeln  Weichweizen
Wirtschaftsjahr
1991/92              17          14           17
1992/93              17          14           17
1993/94              17          14           17
1994/95              17          14           17
1995/96              17          14           17
1996/97              17          14           17
1997/98              17          14           17
1998/99              17          14           17
1999/00              17          14           17
2000/01              17          14           17
2001/02              17          14           17
2002/03              17          14           17
2003/04              17          14           17
2004/05              17          14           17
2005/06              17          14           17
2006/07              17          14           17
2007/08              17          14           17
2008/09              17          14           17
2009/10              17          14           17
2010/11              17          14           17
2011/12              17          14           17
2012/13              17          14           17
2013/14              17          14           17
2014/15              17          14           17
2015/16              17          14           17
2016/17              17          14           17
2017/18              17          14           17
2018/19              17          14           17
2019/20              17          14           17
2020/21              17          14           17
2021/22              17          14           17
2022/23              17          14           17
2023/24              17          14           17
2024/25              17          14           17

In [41]:

# Compare balance positions across products for a common year
comparison_year = "1991/92"

position_columns = [
    "Bilanz Oberbegriff",
    "Bilanz Position",
    "Bilanz Einheit",
]

year_df = df.loc[
    df["Wirtschaftsjahr"] == comparison_year,
    ["Bilanz Produkt"] + position_columns,
].copy()

# Normalize whitespace for comparison only
for column in position_columns:
    year_df[column] = (
        year_df[column]
        .astype("string")
        .str.replace(r"\s+", " ", regex=True)
        .str.strip()
    )

# Extract unique balance positions for each product
positions_by_product = {}

for product in ["Gerste", "Weichweizen", "Kartoffeln"]:
    positions = (
        year_df.loc[
            year_df["Bilanz Produkt"] == product,
            position_columns,
        ]
        .drop_duplicates()
        .sort_values(position_columns)
        .reset_index(drop=True)
    )

    positions_by_product[product] = positions

    print(f"\n{product}: {len(positions)} unique balance positions")
    display(positions)

Gerste: 17 unique balance positions

,Bilanz Oberbegriff,Bilanz Position,Bilanz Einheit
0,Anfangsbestand,Anfangsbestand,1 000 t Produktgewicht
1,Ausfuhr,Ausfuhr,1 000 t Produktgewicht
2,Detailposition,Futter,1 000 t Produktgewicht
3,Detailposition,Industrielle Verwertung,1 000 t Produktgewicht
4,Detailposition,Industrielle Verwertung für Energie,1 000 t Produktgewicht
5,Detailposition,Inlandsverwendung insgesamt,1 000 t Produktgewicht
6,Detailposition,Nahrungsverbrauch Ausbeute in %,%
7,Detailposition,Nahrungsverbrauch in Getreidewert,1 000 t Getreidewert
8,Detailposition,Nahrungsverbrauch in Getreidewert in kg je Kopf,1 000 t Getreidewert
9,Detailposition,Saatgut,1 000 t Produktgewicht
10,Detailposition,Verluste,1 000 t Produktgewicht
11,Einfuhr,Einfuhr,1 000 t Produktgewicht
12,Endbestand,Endbestand,1 000 t Produktgewicht
13,Produktion,Verwendbare Erzeugung,1 000 t Produktgewicht
14,Selbstversorgungsgrad,Selbstversorgungsgrad in %,%
15,Verbrauch,Nahrungsverbrauch in Produktgewicht,1 000 t Produktgewicht
16,Verbrauch je Kopf,Nahrungsverbrauch in Produktgewicht in kg je Kopf,Kilogramm Mehlwert

Weichweizen: 17 unique balance positions

,Bilanz Oberbegriff,Bilanz Position,Bilanz Einheit
0,Anfangsbestand,Anfangsbestand,1 000 t Produktgewicht
1,Ausfuhr,Ausfuhr,1 000 t Produktgewicht
2,Detailposition,Futter,1 000 t Produktgewicht
3,Detailposition,Industrielle Verwertung,1 000 t Produktgewicht
4,Detailposition,Industrielle Verwertung für Energie,1 000 t Produktgewicht
5,Detailposition,Inlandsverwendung insgesamt,1 000 t Produktgewicht
6,Detailposition,Nahrungsverbrauch Ausbeute in %,%
7,Detailposition,Nahrungsverbrauch in Getreidewert,1 000 t Getreidewert
8,Detailposition,Nahrungsverbrauch in Getreidewert in kg je Kopf,Kilogramm Getreidewert
9,Detailposition,Saatgut,1 000 t Produktgewicht
10,Detailposition,Verluste,1 000 t Produktgewicht
11,Einfuhr,Einfuhr,1 000 t Produktgewicht
12,Endbestand,Endbestand,1 000 t Produktgewicht
13,Produktion,Verwendbare Erzeugung,1 000 t Produktgewicht
14,Selbstversorgungsgrad,Selbstversorgungsgrad in %,%
15,Verbrauch,Nahrungsverbrauch in Produktgewicht,1 000 t Produktgewicht
16,Verbrauch je Kopf,Nahrungsverbrauch in Produktgewicht in kg je Kopf,Kilogramm Mehlwert

Kartoffeln: 14 unique balance positions

,Bilanz Oberbegriff,Bilanz Position,Bilanz Einheit
0,Ausfuhr,Ausfuhr,1 000 t Produktgewicht
1,Bestandsänderung,Bestandsänderung,1 000 t Produktgewicht
2,Detailposition,Futter,1 000 t Produktgewicht
3,Detailposition,Industrielle Verwertung,1 000 t Produktgewicht
4,Detailposition,Inlandsverwendung,1 000 t Produktgewicht
5,Detailposition,Nahrungsverbrauch Kartoffelerzeugnisse,Kilogramm Frischkartoffelwert
6,Detailposition,Saatgut,1 000 t Produktgewicht
7,Detailposition,Verluste,1 000 t Produktgewicht
8,Einfuhr,Einfuhr,1 000 t Produktgewicht
9,Gesamterzeugung,Gesamterzeugung,1 000 t Produktgewicht
10,Selbstversorgungsgrad,Selbstversorgungsgrad in %,%
11,Verbrauch,Nahrungsverbrauch,1 000 t Produktgewicht
12,Verbrauch je Kopf,Nahrungsverbrauch in kg je Kopf,Kilogramm Produktgewicht
13,Verwendbare Erzeugung,Verwendbare Erzeugung,1 000 t Produktgewicht

In [35]:
# Data quality note: The dataset contains 17 records per year for barley and soft wheat and 14 records per year for potatoes. A comparison of balance positions for the financial year 1991/92 showed that the product balances differ in their structure and include product-specific positions and differently named categories. The differences in record counts were also verified against the original source data. No records have been deleted, and no missing values have been replaced. The original data structure is retained for further analysis.

In [43]:
# Count records by product
product_counts = df["Bilanz Produkt"].value_counts().sort_index()

display(product_counts)

Bilanz Produkt
Gerste         578
Kartoffeln     476
Weichweizen    578
Name: count, dtype: int64

In [44]:
# Standardize whitespace in text columns
text_columns = df.select_dtypes(include=["str"]).columns

for column in text_columns:
    df[column] = (
        df[column]
        .str.replace(r"\s+", " ", regex=True)
        .str.strip()
    )

# Check dataset dimensions
print(f"Dataset shape: {df.shape}")

Dataset shape: (1632, 6)

In [45]:
# Final data quality checks
print(f"Number of rows: {df.shape[0]}")
print(f"Number of columns: {df.shape[1]}")
print(f"Duplicate rows: {df.duplicated().sum()}")
print(f"Missing values in Bilanz Wert: {df['Bilanz Wert'].isna().sum()}")

# Count records by product
display(df["Bilanz Produkt"].value_counts().sort_index())

# Inspect data types
display(df.dtypes)

Number of rows: 1632
Number of columns: 6
Duplicate rows: 0
Missing values in Bilanz Wert: 64

Bilanz Produkt
Gerste         578
Kartoffeln     476
Weichweizen    578
Name: count, dtype: int64

Wirtschaftsjahr           str
Bilanz Produkt            str
Bilanz Oberbegriff        str
Bilanz Position           str
Bilanz Einheit            str
Bilanz Wert           float64
dtype: object

In [47]:
%pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   ---------------------------------------- 0/2 [et-xmlfile]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

In [48]:
# Save the cleaned dataset
output_dir = project_dir / "data" / "processed"
output_dir.mkdir(parents=True, exist_ok=True)

output_path = output_dir / "ble_cleaned_supply_balance_1991-2025.xlsx"
df.to_excel(output_path, index=False)

print(f"File saved: {output_path}")

File saved: c:\Users\incog\Desktop\Portfolio_Project_Agriculture\data\processed\ble_cleaned_supply_balance_1991-2025.xlsx