In [9]:
import pandas as pd

# Dateipfad
file_path = r"C:\Users\incog\Desktop\Portfolio_Project_Agriculture\data\processed\ble_cleaned_supply_balance_with_quotas_heute_1991-2025.xlsx"

# Excel-Datei einlesen
df_with_quotas = pd.read_excel(file_path)

# Erste Ergebnisse anzeigen
display(df_with_quotas.head())

# Datensatz überprüfen
print("Anzahl Zeilen:", len(df_with_quotas))
print("Anzahl Spalten:", len(df_with_quotas.columns))
print("\nSpaltennamen:")
print(df_with_quotas.columns.tolist())

print("\nDatentypen:")
print(df_with_quotas.dtypes)

,Wirtschaftsjahr,Bilanz Produkt,Ausfuhr,Einfuhr,Inlandsverwendung,Inlandsverwendung insgesamt,Selbstversorgungsgrad in %,Verwendbare Erzeugung,Inlandsverwendung standardisiert,Importquote in %,...,Nahrungsverbrauch Kartoffelerzeugnisse_y,Nahrungsverbrauch in Getreidewert_y,Nahrungsverbrauch in Getreidewert in kg je Kopf_y,Nahrungsverbrauch in Produktgewicht_y,Nahrungsverbrauch in Produktgewicht in kg je Kopf_y,Nahrungsverbrauch in Produktgewicht in kg je Kopf/ dgl. kg je Kopf_y,Nahrungsverbrauch in Produktgewicht/ in Mehlwert_y,Nahrungsverbrauch in kg je Kopf_y,Saatgut_y,Verluste_y
0,1991/92,Gerste,3537.0,1233.0,NaN,10637.0,136.26022,14494.0,10637.0,11.591614,...,NaN,10.0,NaN,8.0,0.09879,NaN,NaN,NaN,388.0,351.0
1,1991/92,Kartoffeln,1002.0,1757.0,10787.0,NaN,90.00000,9737.0,10787.0,16.288125,...,29.9,NaN,NaN,NaN,NaN,NaN,NaN,74.0,818.0,260.0
2,1991/92,Weichweizen,4941.0,1440.0,NaN,11639.0,142.03110,16531.0,11639.0,12.372197,...,NaN,5049.0,NaN,3919.0,48.39467,NaN,NaN,NaN,473.0,402.0
3,1992/93,Gerste,2725.0,1035.0,NaN,10502.0,116.13026,12196.0,10502.0,9.855266,...,NaN,10.0,NaN,8.0,0.09879,NaN,NaN,NaN,367.0,306.0
4,1992/93,Kartoffeln,1122.0,1458.0,10644.0,NaN,97.00000,10358.0,10644.0,13.697858,...,29.1,NaN,NaN,NaN,NaN,NaN,NaN,73.3,731.0,235.0

Anzahl Zeilen: 102
Anzahl Spalten: 41

Spaltennamen:
['Wirtschaftsjahr', 'Bilanz Produkt', 'Ausfuhr', 'Einfuhr', 'Inlandsverwendung', 'Inlandsverwendung insgesamt', 'Selbstversorgungsgrad in %', 'Verwendbare Erzeugung', 'Inlandsverwendung standardisiert', 'Importquote in %', 'Exportquote in %', 'Futter_x', 'Industrielle Verwertung_x', 'Industrielle Verwertung für Energie_x', 'Nahrungsverbrauch_x', 'Nahrungsverbrauch Ausbeute in %_x', 'Nahrungsverbrauch Kartoffelerzeugnisse_x', 'Nahrungsverbrauch in Getreidewert_x', 'Nahrungsverbrauch in Getreidewert in kg je Kopf_x', 'Nahrungsverbrauch in Produktgewicht_x', 'Nahrungsverbrauch in Produktgewicht in kg je Kopf_x', 'Nahrungsverbrauch in Produktgewicht in kg je Kopf/ dgl. kg je Kopf_x', 'Nahrungsverbrauch in Produktgewicht/ in Mehlwert_x', 'Nahrungsverbrauch in kg je Kopf_x', 'Saatgut_x', 'Verluste_x', 'Futter_y', 'Industrielle Verwertung_y', 'Industrielle Verwertung für Energie_y', 'Nahrungsverbrauch_y', 'Nahrungsverbrauch Ausbeute in %_y', 'Nahrungsverbrauch Kartoffelerzeugnisse_y', 'Nahrungsverbrauch in Getreidewert_y', 'Nahrungsverbrauch in Getreidewert in kg je Kopf_y', 'Nahrungsverbrauch in Produktgewicht_y', 'Nahrungsverbrauch in Produktgewicht in kg je Kopf_y', 'Nahrungsverbrauch in Produktgewicht in kg je Kopf/ dgl. kg je Kopf_y', 'Nahrungsverbrauch in Produktgewicht/ in Mehlwert_y', 'Nahrungsverbrauch in kg je Kopf_y', 'Saatgut_y', 'Verluste_y']

Datentypen:
Wirtschaftsjahr                                                             str
Bilanz Produkt                                                              str
Ausfuhr                                                                 float64
Einfuhr                                                                 float64
Inlandsverwendung                                                       float64
Inlandsverwendung insgesamt                                             float64
Selbstversorgungsgrad in %                                              float64
Verwendbare Erzeugung                                                   float64
Inlandsverwendung standardisiert                                        float64
Importquote in %                                                        float64
Exportquote in %                                                        float64
Futter_x                                                                float64
Industrielle Verwertung_x                                               float64
Industrielle Verwertung für Energie_x                                   float64
Nahrungsverbrauch_x                                                     float64
Nahrungsverbrauch Ausbeute in %_x                                       float64
Nahrungsverbrauch Kartoffelerzeugnisse_x                                float64
Nahrungsverbrauch in Getreidewert_x                                     float64
Nahrungsverbrauch in Getreidewert in kg je Kopf_x                       float64
Nahrungsverbrauch in Produktgewicht_x                                   float64
Nahrungsverbrauch in Produktgewicht in kg je Kopf_x                     float64
Nahrungsverbrauch in Produktgewicht in kg je Kopf/ dgl. kg je Kopf_x    float64
Nahrungsverbrauch in Produktgewicht/ in Mehlwert_x                      float64
Nahrungsverbrauch in kg je Kopf_x                                       float64
Saatgut_x                                                               float64
Verluste_x                                                              float64
Futter_y                                                                float64
Industrielle Verwertung_y                                               float64
Industrielle Verwertung für Energie_y                                   float64
Nahrungsverbrauch_y                                                     float64
Nahrungsverbrauch Ausbeute in %_y                                       float64
Nahrungsverbrauch Kartoffelerzeugnisse_y                                float64
Nahrungsverbrauch in Getreidewert_y                                     float64
Nahrungsverbrauch in Getreidewert in kg je Kopf_y                       float64
Nahrungsverbrauch in Produktgewicht_y                                   float64
Nahrungsverbrauch in Produktgewicht in kg je Kopf_y                     float64
Nahrungsverbrauch in Produktgewicht in kg je Kopf/ dgl. kg je Kopf_y    float64
Nahrungsverbrauch in Produktgewicht/ in Mehlwert_y                      float64
Nahrungsverbrauch in kg je Kopf_y                                       float64
Saatgut_y                                                               float64
Verluste_y                                                              float64
dtype: object

In [11]:
import pandas as pd

# Dateipfad
file_path = r"C:\Users\incog\Desktop\Portfolio_Project_Agriculture\data\processed\ble_cleaned_supply_balance_with_quotas_heute_1991-2025.xlsx"

# Excel-Datei einlesen
df_with_quotas = pd.read_excel(file_path)

# _x und _y am Ende der Spaltennamen entfernen
df_with_quotas.columns = df_with_quotas.columns.str.replace(
    r'_[xy]$', '', regex=True
)

# Erste Ergebnisse anzeigen
display(df_with_quotas.head())

# Datensatz überprüfen
print("Anzahl Zeilen:", len(df_with_quotas))
print("Anzahl Spalten:", len(df_with_quotas.columns))

print("\nBereinigte Spaltennamen:")
print(df_with_quotas.columns.tolist())

print("\nDatentypen:")
print(df_with_quotas.dtypes)

# Prüfen, ob doppelte Spaltennamen entstanden sind
print("\nDoppelte Spaltennamen:")
print(df_with_quotas.columns[df_with_quotas.columns.duplicated()].tolist())

,Wirtschaftsjahr,Bilanz Produkt,Ausfuhr,Einfuhr,Inlandsverwendung,Inlandsverwendung insgesamt,Selbstversorgungsgrad in %,Verwendbare Erzeugung,Inlandsverwendung standardisiert,Importquote in %,...,Nahrungsverbrauch Kartoffelerzeugnisse,Nahrungsverbrauch in Getreidewert,Nahrungsverbrauch in Getreidewert in kg je Kopf,Nahrungsverbrauch in Produktgewicht,Nahrungsverbrauch in Produktgewicht in kg je Kopf,Nahrungsverbrauch in Produktgewicht in kg je Kopf/ dgl. kg je Kopf,Nahrungsverbrauch in Produktgewicht/ in Mehlwert,Nahrungsverbrauch in kg je Kopf,Saatgut,Verluste
0,1991/92,Gerste,3537.0,1233.0,NaN,10637.0,136.26022,14494.0,10637.0,11.591614,...,NaN,10.0,NaN,8.0,0.09879,NaN,NaN,NaN,388.0,351.0
1,1991/92,Kartoffeln,1002.0,1757.0,10787.0,NaN,90.00000,9737.0,10787.0,16.288125,...,29.9,NaN,NaN,NaN,NaN,NaN,NaN,74.0,818.0,260.0
2,1991/92,Weichweizen,4941.0,1440.0,NaN,11639.0,142.03110,16531.0,11639.0,12.372197,...,NaN,5049.0,NaN,3919.0,48.39467,NaN,NaN,NaN,473.0,402.0
3,1992/93,Gerste,2725.0,1035.0,NaN,10502.0,116.13026,12196.0,10502.0,9.855266,...,NaN,10.0,NaN,8.0,0.09879,NaN,NaN,NaN,367.0,306.0
4,1992/93,Kartoffeln,1122.0,1458.0,10644.0,NaN,97.00000,10358.0,10644.0,13.697858,...,29.1,NaN,NaN,NaN,NaN,NaN,NaN,73.3,731.0,235.0

Anzahl Zeilen: 102
Anzahl Spalten: 41

Bereinigte Spaltennamen:
['Wirtschaftsjahr', 'Bilanz Produkt', 'Ausfuhr', 'Einfuhr', 'Inlandsverwendung', 'Inlandsverwendung insgesamt', 'Selbstversorgungsgrad in %', 'Verwendbare Erzeugung', 'Inlandsverwendung standardisiert', 'Importquote in %', 'Exportquote in %', 'Futter', 'Industrielle Verwertung', 'Industrielle Verwertung für Energie', 'Nahrungsverbrauch', 'Nahrungsverbrauch Ausbeute in %', 'Nahrungsverbrauch Kartoffelerzeugnisse', 'Nahrungsverbrauch in Getreidewert', 'Nahrungsverbrauch in Getreidewert in kg je Kopf', 'Nahrungsverbrauch in Produktgewicht', 'Nahrungsverbrauch in Produktgewicht in kg je Kopf', 'Nahrungsverbrauch in Produktgewicht in kg je Kopf/ dgl. kg je Kopf', 'Nahrungsverbrauch in Produktgewicht/ in Mehlwert', 'Nahrungsverbrauch in kg je Kopf', 'Saatgut', 'Verluste', 'Futter', 'Industrielle Verwertung', 'Industrielle Verwertung für Energie', 'Nahrungsverbrauch', 'Nahrungsverbrauch Ausbeute in %', 'Nahrungsverbrauch Kartoffelerzeugnisse', 'Nahrungsverbrauch in Getreidewert', 'Nahrungsverbrauch in Getreidewert in kg je Kopf', 'Nahrungsverbrauch in Produktgewicht', 'Nahrungsverbrauch in Produktgewicht in kg je Kopf', 'Nahrungsverbrauch in Produktgewicht in kg je Kopf/ dgl. kg je Kopf', 'Nahrungsverbrauch in Produktgewicht/ in Mehlwert', 'Nahrungsverbrauch in kg je Kopf', 'Saatgut', 'Verluste']

Datentypen:
Wirtschaftsjahr                                                           str
Bilanz Produkt                                                            str
Ausfuhr                                                               float64
Einfuhr                                                               float64
Inlandsverwendung                                                     float64
Inlandsverwendung insgesamt                                           float64
Selbstversorgungsgrad in %                                            float64
Verwendbare Erzeugung                                                 float64
Inlandsverwendung standardisiert                                      float64
Importquote in %                                                      float64
Exportquote in %                                                      float64
Futter                                                                float64
Industrielle Verwertung                                               float64
Industrielle Verwertung für Energie                                   float64
Nahrungsverbrauch                                                     float64
Nahrungsverbrauch Ausbeute in %                                       float64
Nahrungsverbrauch Kartoffelerzeugnisse                                float64
Nahrungsverbrauch in Getreidewert                                     float64
Nahrungsverbrauch in Getreidewert in kg je Kopf                       float64
Nahrungsverbrauch in Produktgewicht                                   float64
Nahrungsverbrauch in Produktgewicht in kg je Kopf                     float64
Nahrungsverbrauch in Produktgewicht in kg je Kopf/ dgl. kg je Kopf    float64
Nahrungsverbrauch in Produktgewicht/ in Mehlwert                      float64
Nahrungsverbrauch in kg je Kopf                                       float64
Saatgut                                                               float64
Verluste                                                              float64
Futter                                                                float64
Industrielle Verwertung                                               float64
Industrielle Verwertung für Energie                                   float64
Nahrungsverbrauch                                                     float64
Nahrungsverbrauch Ausbeute in %                                       float64
Nahrungsverbrauch Kartoffelerzeugnisse                                float64
Nahrungsverbrauch in Getreidewert                                     float64
Nahrungsverbrauch in Getreidewert in kg je Kopf                       float64
Nahrungsverbrauch in Produktgewicht                                   float64
Nahrungsverbrauch in Produktgewicht in kg je Kopf                     float64
Nahrungsverbrauch in Produktgewicht in kg je Kopf/ dgl. kg je Kopf    float64
Nahrungsverbrauch in Produktgewicht/ in Mehlwert                      float64
Nahrungsverbrauch in kg je Kopf                                       float64
Saatgut                                                               float64
Verluste                                                              float64
dtype: object

Doppelte Spaltennamen:
['Futter', 'Industrielle Verwertung', 'Industrielle Verwertung für Energie', 'Nahrungsverbrauch', 'Nahrungsverbrauch Ausbeute in %', 'Nahrungsverbrauch Kartoffelerzeugnisse', 'Nahrungsverbrauch in Getreidewert', 'Nahrungsverbrauch in Getreidewert in kg je Kopf', 'Nahrungsverbrauch in Produktgewicht', 'Nahrungsverbrauch in Produktgewicht in kg je Kopf', 'Nahrungsverbrauch in Produktgewicht in kg je Kopf/ dgl. kg je Kopf', 'Nahrungsverbrauch in Produktgewicht/ in Mehlwert', 'Nahrungsverbrauch in kg je Kopf', 'Saatgut', 'Verluste']

In [12]:

# Bereinigte Excel-Datei speichern
output_path = r"C:\Users\incog\Desktop\Portfolio_Project_Agriculture\data\processed\ble_cleaned_supply_balance_food_use_1991-2025.xlsx"

df_with_quotas.to_excel(output_path, index=False)

print("Datei erfolgreich gespeichert unter:")
print(output_path)

Datei erfolgreich gespeichert unter:
C:\Users\incog\Desktop\Portfolio_Project_Agriculture\data\processed\ble_cleaned_supply_balance_food_use_1991-2025.xlsx