In [31]:
import pandas as pd
from pathlib import Path

# Pfad zum Datenordner
data_path = Path(
    r"C:\Users\incog\Desktop\Portfolio_Project_Agriculture\data\processed"
)

# Excel-Dateien einlesen
df_net_trade_balance = pd.read_excel(
    data_path / "ble_net_trade_balance_1991-2025.xlsx"
)

df_supply_balance = pd.read_excel(
    data_path / "ble_cleaned_supply_balance_food_use_1991-2025.xlsx"
)

# Erste Zeilen anzeigen
print(df_net_trade_balance.head())
print(df_supply_balance.head())

  Wirtschaftsjahr Bilanz Produkt  Einfuhr  Ausfuhr  Nettohandelsbilanz
0         1991/92         Gerste   1233.0   3537.0              2304.0
1         1991/92     Kartoffeln   1757.0   1002.0              -755.0
2         1991/92    Weichweizen   1440.0   4941.0              3501.0
3         1992/93         Gerste   1035.0   2725.0              1690.0
4         1992/93     Kartoffeln   1458.0   1122.0              -336.0
  Wirtschaftsjahr Bilanz Produkt  Ausfuhr  Einfuhr  Inlandsverwendung  \
0         1991/92         Gerste   3537.0   1233.0                NaN
1         1991/92     Kartoffeln   1002.0   1757.0            10787.0
2         1991/92    Weichweizen   4941.0   1440.0                NaN
3         1992/93         Gerste   2725.0   1035.0                NaN
4         1992/93     Kartoffeln   1122.0   1458.0            10644.0

   Inlandsverwendung insgesamt  Selbstversorgungsgrad in %  \
0                      10637.0                   136.26022
1                          NaN                    90.00000
2                      11639.0                   142.03110
3                      10502.0                   116.13026
4                          NaN                    97.00000

   Verwendbare Erzeugung  Inlandsverwendung standardisiert  Importquote in %  \
0                14494.0                           10637.0         11.591614
1                 9737.0                           10787.0         16.288125
2                16531.0                           11639.0         12.372197
3                12196.0                           10502.0          9.855266
4                10358.0                           10644.0         13.697858

   ...  Nahrungsverbrauch Kartoffelerzeugnisse.1  \
0  ...                                       NaN
1  ...                                      29.9
2  ...                                       NaN
3  ...                                       NaN
4  ...                                      29.1

   Nahrungsverbrauch in Getreidewert.1  \
0                                 10.0
1                                  NaN
2                               5049.0
3                                 10.0
4                                  NaN

   Nahrungsverbrauch in Getreidewert in kg je Kopf.1  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

   Nahrungsverbrauch in Produktgewicht.1  \
0                                    8.0
1                                    NaN
2                                 3919.0
3                                    8.0
4                                    NaN

   Nahrungsverbrauch in Produktgewicht in kg je Kopf.1  \
0                                            0.09879
1                                                NaN
2                                           48.39467
3                                            0.09879
4                                                NaN

   Nahrungsverbrauch in Produktgewicht in kg je Kopf/ dgl. kg je Kopf.1  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

   Nahrungsverbrauch in Produktgewicht/ in Mehlwert.1  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

   Nahrungsverbrauch in kg je Kopf.1  Saatgut.1  Verluste.1
0                                NaN      388.0       351.0
1                               74.0      818.0       260.0
2                                NaN      473.0       402.0
3                                NaN      367.0       306.0
4                               73.3      731.0       235.0

[5 rows x 41 columns]

In [32]:
import pandas as pd
from pathlib import Path

data_path = Path(
    r"C:\Users\incog\Desktop\Portfolio_Project_Agriculture\data\processed"
)

# Dateien einlesen
df_net_trade_balance = pd.read_excel(
    data_path / "ble_net_trade_balance_1991-2025.xlsx"
)

df_supply_balance = pd.read_excel(
    data_path / "ble_cleaned_supply_balance_food_use_1991-2025.xlsx"
)

# Spaltennamen ausgeben
print("Net Trade Balance:")
print(df_net_trade_balance.columns.tolist())

print("\nSupply Balance:")
print(df_supply_balance.columns.tolist())

Net Trade Balance:
['Wirtschaftsjahr', 'Bilanz Produkt', 'Einfuhr', 'Ausfuhr', 'Nettohandelsbilanz']

Supply Balance:
['Wirtschaftsjahr', 'Bilanz Produkt', 'Ausfuhr', 'Einfuhr', 'Inlandsverwendung', 'Inlandsverwendung insgesamt', 'Selbstversorgungsgrad in %', 'Verwendbare Erzeugung', 'Inlandsverwendung standardisiert', 'Importquote in %', 'Exportquote in %', 'Futter', 'Industrielle Verwertung', 'Industrielle Verwertung für Energie', 'Nahrungsverbrauch', 'Nahrungsverbrauch Ausbeute in %', 'Nahrungsverbrauch Kartoffelerzeugnisse', 'Nahrungsverbrauch in Getreidewert', 'Nahrungsverbrauch in Getreidewert in kg je Kopf', 'Nahrungsverbrauch in Produktgewicht', 'Nahrungsverbrauch in Produktgewicht in kg je Kopf', 'Nahrungsverbrauch in Produktgewicht in kg je Kopf/ dgl. kg je Kopf', 'Nahrungsverbrauch in Produktgewicht/ in Mehlwert', 'Nahrungsverbrauch in kg je Kopf', 'Saatgut', 'Verluste', 'Futter.1', 'Industrielle Verwertung.1', 'Industrielle Verwertung für Energie.1', 'Nahrungsverbrauch.1', 'Nahrungsverbrauch Ausbeute in %.1', 'Nahrungsverbrauch Kartoffelerzeugnisse.1', 'Nahrungsverbrauch in Getreidewert.1', 'Nahrungsverbrauch in Getreidewert in kg je Kopf.1', 'Nahrungsverbrauch in Produktgewicht.1', 'Nahrungsverbrauch in Produktgewicht in kg je Kopf.1', 'Nahrungsverbrauch in Produktgewicht in kg je Kopf/ dgl. kg je Kopf.1', 'Nahrungsverbrauch in Produktgewicht/ in Mehlwert.1', 'Nahrungsverbrauch in kg je Kopf.1', 'Saatgut.1', 'Verluste.1']

In [36]:

import pandas as pd
from pathlib import Path

# Datenpfad
data_path = Path(
    r"C:\Users\incog\Desktop\Portfolio_Project_Agriculture\data\processed"
)

# Excel-Dateien einlesen
df_net_trade_balance = pd.read_excel(
    data_path / "ble_net_trade_balance_1991-2025.xlsx"
)

df_supply_balance = pd.read_excel(
    data_path / "ble_cleaned_supply_balance_food_use_1991-2025.xlsx"
)

# Nur die benötigten Spalten aus der Net-Trade-Tabelle auswählen
df_net_trade_selected = df_net_trade_balance[
    ["Wirtschaftsjahr", "Bilanz Produkt", "Nettohandelsbilanz"]
]

# Prüfen, ob die Schlüssel in der Net-Trade-Tabelle eindeutig sind
if df_net_trade_selected.duplicated(
    subset=["Wirtschaftsjahr", "Bilanz Produkt"]
).any():
    raise ValueError(
        "Doppelte Schlüssel in der Net-Trade-Tabelle gefunden. "
        "Bitte die Duplikate prüfen."
    )

# Merge über Wirtschaftsjahr und Bilanz Produkt
df_merged = df_supply_balance.merge(
    df_net_trade_selected,
    on=["Wirtschaftsjahr", "Bilanz Produkt"],
    how="left",
    validate="many_to_one",
    indicator=True
)

# Anzahl der nicht zugeordneten Zeilen prüfen
print("Zeilen in Supply Balance:", len(df_supply_balance))
print("Zeilen nach Merge:", len(df_merged))
print(
    "Nicht zugeordnete Zeilen:",
    (df_merged["_merge"] == "left_only").sum()
)

# Hilfsspalte entfernen
df_merged = df_merged.drop(columns="_merge")

# Ergebnis als neue Excel-Datei speichern
output_file = data_path / (
    "ble_supply_balance_final_1991-2025.xlsx"
)

df_merged.to_excel(output_file, index=False)

print("Datei gespeichert unter:", output_file)
print(df_merged.head())

Zeilen in Supply Balance: 102
Zeilen nach Merge: 102
Nicht zugeordnete Zeilen: 0
Datei gespeichert unter: C:\Users\incog\Desktop\Portfolio_Project_Agriculture\data\processed\ble_supply_balance_final_1991-2025.xlsx
  Wirtschaftsjahr Bilanz Produkt  Ausfuhr  Einfuhr  Inlandsverwendung  \
0         1991/92         Gerste   3537.0   1233.0                NaN
1         1991/92     Kartoffeln   1002.0   1757.0            10787.0
2         1991/92    Weichweizen   4941.0   1440.0                NaN
3         1992/93         Gerste   2725.0   1035.0                NaN
4         1992/93     Kartoffeln   1122.0   1458.0            10644.0

   Inlandsverwendung insgesamt  Selbstversorgungsgrad in %  \
0                      10637.0                   136.26022
1                          NaN                    90.00000
2                      11639.0                   142.03110
3                      10502.0                   116.13026
4                          NaN                    97.00000

   Verwendbare Erzeugung  Inlandsverwendung standardisiert  Importquote in %  \
0                14494.0                           10637.0         11.591614
1                 9737.0                           10787.0         16.288125
2                16531.0                           11639.0         12.372197
3                12196.0                           10502.0          9.855266
4                10358.0                           10644.0         13.697858

   ...  Nahrungsverbrauch in Getreidewert.1  \
0  ...                                 10.0
1  ...                                  NaN
2  ...                               5049.0
3  ...                                 10.0
4  ...                                  NaN

   Nahrungsverbrauch in Getreidewert in kg je Kopf.1  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

   Nahrungsverbrauch in Produktgewicht.1  \
0                                    8.0
1                                    NaN
2                                 3919.0
3                                    8.0
4                                    NaN

   Nahrungsverbrauch in Produktgewicht in kg je Kopf.1  \
0                                            0.09879
1                                                NaN
2                                           48.39467
3                                            0.09879
4                                                NaN

   Nahrungsverbrauch in Produktgewicht in kg je Kopf/ dgl. kg je Kopf.1  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

   Nahrungsverbrauch in Produktgewicht/ in Mehlwert.1  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

   Nahrungsverbrauch in kg je Kopf.1  Saatgut.1  Verluste.1  \
0                                NaN      388.0       351.0
1                               74.0      818.0       260.0
2                                NaN      473.0       402.0
3                                NaN      367.0       306.0
4                               73.3      731.0       235.0

   Nettohandelsbilanz
0              2304.0
1              -755.0
2              3501.0
3              1690.0
4              -336.0

[5 rows x 42 columns]

In [37]:
import pandas as pd
from pathlib import Path

data_path = Path(
    r"C:\Users\incog\Desktop\Portfolio_Project_Agriculture\data\processed"
)

# Finale Datei einlesen
df_final = pd.read_excel(
    data_path / "ble_supply_balance_final_1991-2025.xlsx"
)

# Grundlegende Prüfung
print("Dimensionen:", df_final.shape)
print("\nSpalten:")
print(df_final.columns.tolist())

print("\nFehlende Werte in Nettohandelsbilanz:")
print(df_final["Nettohandelsbilanz"].isna().sum())

print("\nDoppelte Schlüssel:")
print(
    df_final.duplicated(
        subset=["Wirtschaftsjahr", "Bilanz Produkt"]
    ).sum()
)

print("\nErste Zeilen:")
print(df_final.head())

Dimensionen: (102, 42)

Spalten:
['Wirtschaftsjahr', 'Bilanz Produkt', 'Ausfuhr', 'Einfuhr', 'Inlandsverwendung', 'Inlandsverwendung insgesamt', 'Selbstversorgungsgrad in %', 'Verwendbare Erzeugung', 'Inlandsverwendung standardisiert', 'Importquote in %', 'Exportquote in %', 'Futter', 'Industrielle Verwertung', 'Industrielle Verwertung für Energie', 'Nahrungsverbrauch', 'Nahrungsverbrauch Ausbeute in %', 'Nahrungsverbrauch Kartoffelerzeugnisse', 'Nahrungsverbrauch in Getreidewert', 'Nahrungsverbrauch in Getreidewert in kg je Kopf', 'Nahrungsverbrauch in Produktgewicht', 'Nahrungsverbrauch in Produktgewicht in kg je Kopf', 'Nahrungsverbrauch in Produktgewicht in kg je Kopf/ dgl. kg je Kopf', 'Nahrungsverbrauch in Produktgewicht/ in Mehlwert', 'Nahrungsverbrauch in kg je Kopf', 'Saatgut', 'Verluste', 'Futter.1', 'Industrielle Verwertung.1', 'Industrielle Verwertung für Energie.1', 'Nahrungsverbrauch.1', 'Nahrungsverbrauch Ausbeute in %.1', 'Nahrungsverbrauch Kartoffelerzeugnisse.1', 'Nahrungsverbrauch in Getreidewert.1', 'Nahrungsverbrauch in Getreidewert in kg je Kopf.1', 'Nahrungsverbrauch in Produktgewicht.1', 'Nahrungsverbrauch in Produktgewicht in kg je Kopf.1', 'Nahrungsverbrauch in Produktgewicht in kg je Kopf/ dgl. kg je Kopf.1', 'Nahrungsverbrauch in Produktgewicht/ in Mehlwert.1', 'Nahrungsverbrauch in kg je Kopf.1', 'Saatgut.1', 'Verluste.1', 'Nettohandelsbilanz']

Fehlende Werte in Nettohandelsbilanz:
0

Doppelte Schlüssel:
0

Erste Zeilen:
  Wirtschaftsjahr Bilanz Produkt  Ausfuhr  Einfuhr  Inlandsverwendung  \
0         1991/92         Gerste   3537.0   1233.0                NaN
1         1991/92     Kartoffeln   1002.0   1757.0            10787.0
2         1991/92    Weichweizen   4941.0   1440.0                NaN
3         1992/93         Gerste   2725.0   1035.0                NaN
4         1992/93     Kartoffeln   1122.0   1458.0            10644.0

   Inlandsverwendung insgesamt  Selbstversorgungsgrad in %  \
0                      10637.0                   136.26022
1                          NaN                    90.00000
2                      11639.0                   142.03110
3                      10502.0                   116.13026
4                          NaN                    97.00000

   Verwendbare Erzeugung  Inlandsverwendung standardisiert  Importquote in %  \
0                14494.0                           10637.0         11.591614
1                 9737.0                           10787.0         16.288125
2                16531.0                           11639.0         12.372197
3                12196.0                           10502.0          9.855266
4                10358.0                           10644.0         13.697858

   ...  Nahrungsverbrauch in Getreidewert.1  \
0  ...                                 10.0
1  ...                                  NaN
2  ...                               5049.0
3  ...                                 10.0
4  ...                                  NaN

   Nahrungsverbrauch in Getreidewert in kg je Kopf.1  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

   Nahrungsverbrauch in Produktgewicht.1  \
0                                    8.0
1                                    NaN
2                                 3919.0
3                                    8.0
4                                    NaN

   Nahrungsverbrauch in Produktgewicht in kg je Kopf.1  \
0                                            0.09879
1                                                NaN
2                                           48.39467
3                                            0.09879
4                                                NaN

   Nahrungsverbrauch in Produktgewicht in kg je Kopf/ dgl. kg je Kopf.1  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

   Nahrungsverbrauch in Produktgewicht/ in Mehlwert.1  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

   Nahrungsverbrauch in kg je Kopf.1  Saatgut.1  Verluste.1  \
0                                NaN      388.0       351.0
1                               74.0      818.0       260.0
2                                NaN      473.0       402.0
3                                NaN      367.0       306.0
4                               73.3      731.0       235.0

   Nettohandelsbilanz
0              2304.0
1              -755.0
2              3501.0
3              1690.0
4              -336.0

[5 rows x 42 columns]

In [38]:

import pandas as pd
from pathlib import Path

data_path = Path(
    r"C:\Users\incog\Desktop\Portfolio_Project_Agriculture\data\processed"
)

# Dateien laden
df_final = pd.read_excel(
    data_path / "ble_supply_balance_final_1991-2025.xlsx"
)

df_net = pd.read_excel(
    data_path / "ble_net_trade_balance_1991-2025.xlsx"
)

keys = ["Wirtschaftsjahr", "Bilanz Produkt"]

# Finale Tabelle mit der Originaldatei vergleichen
check = df_final.merge(
    df_net[keys + ["Nettohandelsbilanz", "Einfuhr", "Ausfuhr"]],
    on=keys,
    how="outer",
    suffixes=("_final", "_original"),
    indicator=True,
    validate="one_to_one"
)

print("=== Merge-Prüfung ===")
print(check["_merge"].value_counts())

print("\n=== Abweichungen ===")

for col in ["Nettohandelsbilanz", "Einfuhr", "Ausfuhr"]:
    final_col = f"{col}_final"
    original_col = f"{col}_original"

    # Numerischer Vergleich, fehlende Werte werden berücksichtigt
    a = pd.to_numeric(check[final_col], errors="coerce")
    b = pd.to_numeric(check[original_col], errors="coerce")

    equal = a.eq(b) | (a.isna() & b.isna())

    print(f"{col}: {int((~equal).sum())} Abweichungen")

    if (~equal).any():
        print(check.loc[
            ~equal,
            keys + [final_col, original_col]
        ].head(10))

print("\n=== Gesamtprüfung ===")
print("Zeilen finale Datei:", len(df_final))
print("Zeilen Original Net Trade:", len(df_net))
print("Zeilen im Vergleich:", len(check))

=== Merge-Prüfung ===
_merge
both          102
left_only       0
right_only      0
Name: count, dtype: int64

=== Abweichungen ===
Nettohandelsbilanz: 0 Abweichungen
Einfuhr: 0 Abweichungen
Ausfuhr: 0 Abweichungen

=== Gesamtprüfung ===
Zeilen finale Datei: 102
Zeilen Original Net Trade: 102
Zeilen im Vergleich: 102

In [39]:
import pandas as pd
from pathlib import Path

# Datenpfad
data_path = Path(
    r"C:\Users\incog\Desktop\Portfolio_Project_Agriculture\data\processed"
)

# Finale Supply-Balance-Datei laden
df_final = pd.read_excel(
    data_path / "ble_supply_balance_final_1991-2025.xlsx"
)

# Domestic-Use-Change-Datei laden
df_domestic_use_change = pd.read_excel(
    data_path / "ble_domestic_use_change_1991-2025.xlsx"
)

# Übersicht
print("Final Supply Balance:", df_final.shape)
print("Domestic Use Change:", df_domestic_use_change.shape)

print("\nSpalten der finalen Datei:")
print(df_final.columns.tolist())

print("\nSpalten der Domestic-Use-Change-Datei:")
print(df_domestic_use_change.columns.tolist())

Final Supply Balance: (102, 42)
Domestic Use Change: (102, 5)

Spalten der finalen Datei:
['Wirtschaftsjahr', 'Bilanz Produkt', 'Ausfuhr', 'Einfuhr', 'Inlandsverwendung', 'Inlandsverwendung insgesamt', 'Selbstversorgungsgrad in %', 'Verwendbare Erzeugung', 'Inlandsverwendung standardisiert', 'Importquote in %', 'Exportquote in %', 'Futter', 'Industrielle Verwertung', 'Industrielle Verwertung für Energie', 'Nahrungsverbrauch', 'Nahrungsverbrauch Ausbeute in %', 'Nahrungsverbrauch Kartoffelerzeugnisse', 'Nahrungsverbrauch in Getreidewert', 'Nahrungsverbrauch in Getreidewert in kg je Kopf', 'Nahrungsverbrauch in Produktgewicht', 'Nahrungsverbrauch in Produktgewicht in kg je Kopf', 'Nahrungsverbrauch in Produktgewicht in kg je Kopf/ dgl. kg je Kopf', 'Nahrungsverbrauch in Produktgewicht/ in Mehlwert', 'Nahrungsverbrauch in kg je Kopf', 'Saatgut', 'Verluste', 'Futter.1', 'Industrielle Verwertung.1', 'Industrielle Verwertung für Energie.1', 'Nahrungsverbrauch.1', 'Nahrungsverbrauch Ausbeute in %.1', 'Nahrungsverbrauch Kartoffelerzeugnisse.1', 'Nahrungsverbrauch in Getreidewert.1', 'Nahrungsverbrauch in Getreidewert in kg je Kopf.1', 'Nahrungsverbrauch in Produktgewicht.1', 'Nahrungsverbrauch in Produktgewicht in kg je Kopf.1', 'Nahrungsverbrauch in Produktgewicht in kg je Kopf/ dgl. kg je Kopf.1', 'Nahrungsverbrauch in Produktgewicht/ in Mehlwert.1', 'Nahrungsverbrauch in kg je Kopf.1', 'Saatgut.1', 'Verluste.1', 'Nettohandelsbilanz']

Spalten der Domestic-Use-Change-Datei:
['Wirtschaftsjahr', 'Bilanz Produkt', 'Inlandsverwendung geprüft', 'Vorjahr', 'Veränderung in %']

In [40]:

import pandas as pd
from pathlib import Path
import numpy as np

data_path = Path(
    r"C:\Users\incog\Desktop\Portfolio_Project_Agriculture\data\processed"
)

# Dateien laden
df_final = pd.read_excel(
    data_path / "ble_supply_balance_final_1991-2025.xlsx"
)

df_domestic = pd.read_excel(
    data_path / "ble_domestic_use_change_1991-2025.xlsx"
)

# Schlüssel und zu vergleichende Spalten
keys = ["Wirtschaftsjahr", "Bilanz Produkt"]
col_final = "Inlandsverwendung standardisiert"
col_domestic = "Inlandsverwendung geprüft"

# Prüfen, ob alle benötigten Spalten existieren
for df, cols, name in [
    (df_final, keys + [col_final], "Final"),
    (df_domestic, keys + [col_domestic], "Domestic Use Change")
]:
    missing = [c for c in cols if c not in df.columns]
    if missing:
        raise ValueError(f"{name}: Fehlende Spalten: {missing}")

# Doppelte Schlüssel prüfen
for df, name in [
    (df_final, "Final"),
    (df_domestic, "Domestic Use Change")
]:
    duplicates = df.duplicated(subset=keys, keep=False)
    print(f"{name} – Zeilen mit doppelten Schlüsseln: {duplicates.sum()}")

# Nur benötigte Spalten auswählen und zusammenführen
check = df_final[keys + [col_final]].merge(
    df_domestic[keys + [col_domestic]],
    on=keys,
    how="outer",
    indicator=True,
    validate="one_to_one"
)

# Vergleich numerisch, mit Toleranz für Rundungsdifferenzen
a = pd.to_numeric(check[col_final], errors="coerce")
b = pd.to_numeric(check[col_domestic], errors="coerce")

both_missing = a.isna() & b.isna()
both_present = a.notna() & b.notna()

equal = both_missing | (
    both_present & np.isclose(a, b, rtol=1e-9, atol=1e-8)
)

matched_keys = check["_merge"].eq("both")
equal_for_matched = equal & matched_keys

print("\n=== Schlüsselabgleich ===")
print(check["_merge"].value_counts())

print("\n=== Wertevergleich ===")
print("Gemeinsame Schlüssel:", matched_keys.sum())
print("Übereinstimmende Werte:", equal_for_matched.sum())
print(
    "Abweichende Werte:",
    (matched_keys & ~equal).sum()
)
print(
    "Fehlende Werte in mindestens einer Datei:",
    (matched_keys & (a.isna() ^ b.isna())).sum()
)

# Abweichungen ausgeben
mismatches = check.loc[
    matched_keys & ~equal,
    keys + [col_final, col_domestic]
]

if not mismatches.empty:
    print("\nErste 20 Abweichungen:")
    print(mismatches.head(20).to_string(index=False))
else:
    print("\nAlle Werte bei gemeinsamen Schlüsseln stimmen überein.")

# Schlüssel, die nur in einer Datei vorkommen
unmatched = check.loc[~matched_keys, keys + ["_merge"]]
if not unmatched.empty:
    print("\nSchlüssel, die nicht in beiden Dateien vorkommen:")
    print(unmatched.to_string(index=False))

Final – Zeilen mit doppelten Schlüsseln: 0
Domestic Use Change – Zeilen mit doppelten Schlüsseln: 0

=== Schlüsselabgleich ===
_merge
both          102
left_only       0
right_only      0
Name: count, dtype: int64

=== Wertevergleich ===
Gemeinsame Schlüssel: 102
Übereinstimmende Werte: 102
Abweichende Werte: 0
Fehlende Werte in mindestens einer Datei: 0

Alle Werte bei gemeinsamen Schlüsseln stimmen überein.

In [41]:
print(df_merged.columns.tolist())

['Wirtschaftsjahr', 'Bilanz Produkt', 'Ausfuhr', 'Einfuhr', 'Inlandsverwendung', 'Inlandsverwendung insgesamt', 'Selbstversorgungsgrad in %', 'Verwendbare Erzeugung', 'Inlandsverwendung standardisiert', 'Importquote in %', 'Exportquote in %', 'Futter', 'Industrielle Verwertung', 'Industrielle Verwertung für Energie', 'Nahrungsverbrauch', 'Nahrungsverbrauch Ausbeute in %', 'Nahrungsverbrauch Kartoffelerzeugnisse', 'Nahrungsverbrauch in Getreidewert', 'Nahrungsverbrauch in Getreidewert in kg je Kopf', 'Nahrungsverbrauch in Produktgewicht', 'Nahrungsverbrauch in Produktgewicht in kg je Kopf', 'Nahrungsverbrauch in Produktgewicht in kg je Kopf/ dgl. kg je Kopf', 'Nahrungsverbrauch in Produktgewicht/ in Mehlwert', 'Nahrungsverbrauch in kg je Kopf', 'Saatgut', 'Verluste', 'Futter.1', 'Industrielle Verwertung.1', 'Industrielle Verwertung für Energie.1', 'Nahrungsverbrauch.1', 'Nahrungsverbrauch Ausbeute in %.1', 'Nahrungsverbrauch Kartoffelerzeugnisse.1', 'Nahrungsverbrauch in Getreidewert.1', 'Nahrungsverbrauch in Getreidewert in kg je Kopf.1', 'Nahrungsverbrauch in Produktgewicht.1', 'Nahrungsverbrauch in Produktgewicht in kg je Kopf.1', 'Nahrungsverbrauch in Produktgewicht in kg je Kopf/ dgl. kg je Kopf.1', 'Nahrungsverbrauch in Produktgewicht/ in Mehlwert.1', 'Nahrungsverbrauch in kg je Kopf.1', 'Saatgut.1', 'Verluste.1', 'Nettohandelsbilanz']

In [52]:

import pandas as pd
from pathlib import Path

# ============================================================
# 1. Dateipfade
# ============================================================

data_dir = Path(
    r"C:\Users\incog\Desktop\Portfolio_Project_Agriculture\data\processed"
)

final_file = data_dir / "ble_supply_balance_final_1991-2025.xlsx"
source_file = data_dir / "ble_domestic_use_change_1991-2025.xlsx"

# ============================================================
# 2. Dateien laden
# ============================================================

df_final = pd.read_excel(final_file)
df_source = pd.read_excel(source_file)

keys = ["Wirtschaftsjahr", "Bilanz Produkt"]

source_cols = [
    "Inlandsverwendung geprüft",
    "Vorjahr",
    "Veränderung in %"
]

rename_cols = {
    "Inlandsverwendung geprüft": "Inlandsverwendung_geprueft",
    "Vorjahr": "Inlandsverwendung_Vorjahr",
    "Veränderung in %": "Inlandsverwendung_Veraenderung_%"
}

# ============================================================
# 3. Spalten prüfen
# ============================================================

for col in keys:
    if col not in df_final.columns:
        raise ValueError(f"Schlüsselspalte fehlt in Finaldatei: {col}")
    if col not in df_source.columns:
        raise ValueError(f"Schlüsselspalte fehlt in Quelldatei: {col}")

missing_source_cols = [
    col for col in source_cols
    if col not in df_source.columns
]

if missing_source_cols:
    raise ValueError(
        f"Fehlende Spalten in Quelldatei: {missing_source_cols}"
    )

# ============================================================
# 4. Schlüssel auf Eindeutigkeit prüfen
# ============================================================

if df_final.duplicated(keys).any():
    raise ValueError("Die Finaldatei enthält doppelte Schlüssel.")

if df_source.duplicated(keys).any():
    raise ValueError("Die Quelldatei enthält doppelte Schlüssel.")

# ============================================================
# 5. Drei Quellspalten vorbereiten
# ============================================================

source_data = df_source[
    keys + source_cols
].rename(columns=rename_cols)

# Bereits vorhandene Zielspalten aus der Finaldatei entfernen,
# damit beim Merge keine _x- und _y-Spalten entstehen.
target_cols = list(rename_cols.values())

df_final_base = df_final.drop(
    columns=[
        col for col in target_cols
        if col in df_final.columns
    ]
)

# ============================================================
# 6. Merge durchführen
# ============================================================

df_merged = df_final_base.merge(
    source_data,
    on=keys,
    how="left",
    validate="one_to_one",
    indicator=True
)

print("=== Merge-Ergebnis ===")
print("Zeilen vorher:", len(df_final))
print("Zeilen nachher:", len(df_merged))
print("Zuordnungen:", int(df_merged["_merge"].eq("both").sum()))
print("Ohne Quelldatensatz:", int(df_merged["_merge"].eq("left_only").sum()))

# Nicht zugeordnete Datensätze anzeigen
unmatched = df_merged["_merge"].eq("left_only")

if unmatched.any():
    print("\nNicht zugeordnete Schlüssel:")
    print(
        df_merged.loc[unmatched, keys]
        .to_string(index=False)
    )

# Merge-Indikator entfernen
df_merged = df_merged.drop(columns="_merge")

# ============================================================
# 7. Ergebnis kontrollieren
# ============================================================

print("\n=== Neue Spalten ===")
for col in target_cols:
    print(f"{col}: vorhanden = {col in df_merged.columns}")

print("\nDimensionen vorher:", df_final.shape)
print("Dimensionen nachher:", df_merged.shape)

suffix_cols = [
    col for col in df_merged.columns
    if col.endswith(("_x", "_y"))
]

print("Spalten mit _x oder _y:", suffix_cols)

if len(df_merged) != len(df_final):
    raise ValueError(
        "Die Zeilenzahl hat sich verändert. Datei wird nicht gespeichert."
    )

if not all(col in df_merged.columns for col in target_cols):
    raise ValueError(
        "Mindestens eine der drei Zielspalten fehlt. Datei wird nicht gespeichert."
    )

if unmatched.any():
    raise ValueError(
        "Nicht alle Datensätze konnten zugeordnet werden. "
        "Bitte Schlüssel prüfen. Datei wurde nicht gespeichert."
    )

# ============================================================
# 8. Finaldatei speichern
# ============================================================

df_merged.to_excel(final_file, index=False)

print("\nFinaldatei erfolgreich gespeichert:")
print(final_file)
print("\n=== Merge abgeschlossen ===")

=== Merge-Ergebnis ===
Zeilen vorher: 102
Zeilen nachher: 102
Zuordnungen: 102
Ohne Quelldatensatz: 0

=== Neue Spalten ===
Inlandsverwendung_geprueft: vorhanden = True
Inlandsverwendung_Vorjahr: vorhanden = True
Inlandsverwendung_Veraenderung_%: vorhanden = True

Dimensionen vorher: (102, 45)
Dimensionen nachher: (102, 45)
Spalten mit _x oder _y: []

Finaldatei erfolgreich gespeichert:
C:\Users\incog\Desktop\Portfolio_Project_Agriculture\data\processed\ble_supply_balance_final_1991-2025.xlsx

=== Merge abgeschlossen ===

In [53]:
import pandas as pd

df_check = pd.read_excel(final_file)

cols = [
    "Inlandsverwendung_geprueft",
    "Inlandsverwendung_Vorjahr",
    "Inlandsverwendung_Veraenderung_%"
]

print("Dimensionen:", df_check.shape)
print("\nFehlende Werte in den drei Spalten:")
print(df_check[cols].isna().sum())

print("\nBeispielwerte:")
print(df_check[["Wirtschaftsjahr", "Bilanz Produkt"] + cols].head(10))

Dimensionen: (102, 45)

Fehlende Werte in den drei Spalten:
Inlandsverwendung_geprueft          0
Inlandsverwendung_Vorjahr           3
Inlandsverwendung_Veraenderung_%    3
dtype: int64

Beispielwerte:
  Wirtschaftsjahr Bilanz Produkt  Inlandsverwendung_geprueft  \
0         1991/92         Gerste                     10637.0
1         1991/92     Kartoffeln                     10787.0
2         1991/92    Weichweizen                     11639.0
3         1992/93         Gerste                     10502.0
4         1992/93     Kartoffeln                     10644.0
5         1992/93    Weichweizen                     11004.0
6         1993/94         Gerste                      9692.0
7         1993/94     Kartoffeln                     11912.0
8         1993/94    Weichweizen                     12943.0
9         1994/95         Gerste                      9901.0

   Inlandsverwendung_Vorjahr  Inlandsverwendung_Veraenderung_%
0                        NaN                               NaN
1                        NaN                               NaN
2                        NaN                               NaN
3                    10637.0                         -1.269155
4                    10787.0                         -1.325670
5                    11639.0                         -5.455795
6                    10502.0                         -7.712817
7                    10644.0                         11.912815
8                    11004.0                         17.620865
9                     9692.0                          2.156418

In [54]:
cols = [
    "Inlandsverwendung_geprueft",
    "Inlandsverwendung_Vorjahr",
    "Inlandsverwendung_Veraenderung_%"
]

# Zeilen anzeigen, in denen Werte fehlen
df_check.loc[
    df_check[cols].isna().any(axis=1),
    ["Wirtschaftsjahr", "Bilanz Produkt"] + cols
]

,Wirtschaftsjahr,Bilanz Produkt,Inlandsverwendung_geprueft,Inlandsverwendung_Vorjahr,Inlandsverwendung_Veraenderung_%
0,1991/92,Gerste,10637.0,NaN,NaN
1,1991/92,Kartoffeln,10787.0,NaN,NaN
2,1991/92,Weichweizen,11639.0,NaN,NaN

In [55]:

import pandas as pd
import numpy as np

# Finale Datei einlesen
df_check = pd.read_excel(final_file)

col1 = "Inlandsverwendung_geprueft"
col2 = "Inlandsverwendung_standardisiert"

# Prüfen, ob beide Spalten existieren
assert col1 in df_check.columns, f"Spalte fehlt: {col1}"
assert col2 in df_check.columns, f"Spalte fehlt: {col2}"

# Numerischer Vergleich; NaN wird separat behandelt
a = pd.to_numeric(df_check[col1], errors="coerce")
b = pd.to_numeric(df_check[col2], errors="coerce")

both_missing = a.isna() & b.isna()
both_present_equal = np.isclose(a, b, rtol=0, atol=1e-9, equal_nan=False)
identical = both_missing | (a.notna() & b.notna() & both_present_equal)

# Ergebnis zusammenfassen
print("Anzahl Zeilen:", len(df_check))
print("Identische Werte:", identical.sum())
print("Abweichende Zeilen:", (~identical).sum())
print("Fehlende Werte in geprueft:", a.isna().sum())
print("Fehlende Werte in standardisiert:", b.isna().sum())

# Abweichungen anzeigen
abweichungen = df_check.loc[
    ~identical,
    ["Wirtschaftsjahr", "Bilanz Produkt", col1, col2]
].copy()

print("\nAbweichungen:")
display(abweichungen)

AssertionError: Spalte fehlt: Inlandsverwendung_standardisiert

In [56]:

for col in df_check.columns:
    if "Inlandsverwendung" in col:
        print(repr(col))

'Inlandsverwendung'
'Inlandsverwendung insgesamt'
'Inlandsverwendung standardisiert'
'Inlandsverwendung_geprueft'
'Inlandsverwendung_Vorjahr'
'Inlandsverwendung_Veraenderung_%'

In [57]:

import pandas as pd
import numpy as np

col1 = "Inlandsverwendung_geprueft"
col2 = "Inlandsverwendung standardisiert"

a = pd.to_numeric(df_check[col1], errors="coerce")
b = pd.to_numeric(df_check[col2], errors="coerce")

# Fehlende Werte auf beiden Seiten gelten als gleich
both_missing = a.isna() & b.isna()

# Numerischer Vergleich mit kleiner Toleranz
both_present_equal = (
    a.notna()
    & b.notna()
    & np.isclose(a, b, rtol=0, atol=1e-9, equal_nan=False)
)

identical = both_missing | both_present_equal

print("Anzahl Zeilen:", len(df_check))
print("Identische Werte:", identical.sum())
print("Abweichende Zeilen:", (~identical).sum())

# Abweichungen anzeigen
abweichungen = df_check.loc[
    ~identical,
    ["Wirtschaftsjahr", "Bilanz Produkt", col1, col2]
]

display(abweichungen)

Anzahl Zeilen: 102
Identische Werte: 102
Abweichende Zeilen: 0

Empty DataFrame
Columns: [Wirtschaftsjahr, Bilanz Produkt, Inlandsverwendung_geprueft, Inlandsverwendung standardisiert]
Index: []

In [51]:

import pandas as pd

col1 = "Inlandsverwendung_geprueft"
col2 = "Inlandsverwendung standardisiert"

a = pd.to_numeric(df_check[col1], errors="coerce")
b = pd.to_numeric(df_check[col2], errors="coerce")

# Exakter Vergleich ohne Toleranz
identisch_exakt = (a == b) | (a.isna() & b.isna())

print("Alle Werte exakt identisch:", identisch_exakt.all())
print("Identische Werte:", identisch_exakt.sum())
print("Abweichende Werte:", (~identisch_exakt).sum())

# Einzelne Wertepaare anzeigen
vergleich = df_check[["Wirtschaftsjahr", "Bilanz Produkt"]].copy()
vergleich[col1] = a
vergleich[col2] = b
vergleich["Exakt_identisch"] = identisch_exakt

display(vergleich)

Alle Werte exakt identisch: True
Identische Werte: 102
Abweichende Werte: 0

,Wirtschaftsjahr,Bilanz Produkt,Inlandsverwendung_geprueft,Inlandsverwendung standardisiert,Exakt_identisch
0,1991/92,Gerste,10637.00000,10637.00000,True
1,1991/92,Kartoffeln,10787.00000,10787.00000,True
2,1991/92,Weichweizen,11639.00000,11639.00000,True
3,1992/93,Gerste,10502.00000,10502.00000,True
4,1992/93,Kartoffeln,10644.00000,10644.00000,True
...,...,...,...,...,...
97,2023/24,Kartoffeln,7205.70000,7205.70000,True
98,2023/24,Weichweizen,17980.67474,17980.67474,True
99,2024/25,Gerste,8540.49858,8540.49858,True
100,2024/25,Kartoffeln,7873.70000,7873.70000,True
101,2024/25,Weichweizen,16889.56155,16889.56155,True

In [58]:

import pandas as pd

# Finale Datei einlesen
df = pd.read_excel(final_file)

# Leerzeichen in Spaltennamen durch Unterstriche ersetzen
df.columns = (
    df.columns
    .str.strip()
    .str.replace(r"\s+", "_", regex=True)
)

# Spaltennamen vorher/nachher anzeigen
print("Bereinigte Spaltennamen:")
print(df.columns.tolist())

# Finale Datei überschreiben
df.to_excel(final_file, index=False)

print("\nFinaldatei erfolgreich gespeichert:")
print(final_file)

Bereinigte Spaltennamen:
['Wirtschaftsjahr', 'Bilanz_Produkt', 'Ausfuhr', 'Einfuhr', 'Inlandsverwendung', 'Inlandsverwendung_insgesamt', 'Selbstversorgungsgrad_in_%', 'Verwendbare_Erzeugung', 'Inlandsverwendung_standardisiert', 'Importquote_in_%', 'Exportquote_in_%', 'Futter', 'Industrielle_Verwertung', 'Industrielle_Verwertung_für_Energie', 'Nahrungsverbrauch', 'Nahrungsverbrauch_Ausbeute_in_%', 'Nahrungsverbrauch_Kartoffelerzeugnisse', 'Nahrungsverbrauch_in_Getreidewert', 'Nahrungsverbrauch_in_Getreidewert_in_kg_je_Kopf', 'Nahrungsverbrauch_in_Produktgewicht', 'Nahrungsverbrauch_in_Produktgewicht_in_kg_je_Kopf', 'Nahrungsverbrauch_in_Produktgewicht_in_kg_je_Kopf/_dgl._kg_je_Kopf', 'Nahrungsverbrauch_in_Produktgewicht/_in_Mehlwert', 'Nahrungsverbrauch_in_kg_je_Kopf', 'Saatgut', 'Verluste', 'Futter.1', 'Industrielle_Verwertung.1', 'Industrielle_Verwertung_für_Energie.1', 'Nahrungsverbrauch.1', 'Nahrungsverbrauch_Ausbeute_in_%.1', 'Nahrungsverbrauch_Kartoffelerzeugnisse.1', 'Nahrungsverbrauch_in_Getreidewert.1', 'Nahrungsverbrauch_in_Getreidewert_in_kg_je_Kopf.1', 'Nahrungsverbrauch_in_Produktgewicht.1', 'Nahrungsverbrauch_in_Produktgewicht_in_kg_je_Kopf.1', 'Nahrungsverbrauch_in_Produktgewicht_in_kg_je_Kopf/_dgl._kg_je_Kopf.1', 'Nahrungsverbrauch_in_Produktgewicht/_in_Mehlwert.1', 'Nahrungsverbrauch_in_kg_je_Kopf.1', 'Saatgut.1', 'Verluste.1', 'Nettohandelsbilanz', 'Inlandsverwendung_geprueft', 'Inlandsverwendung_Vorjahr', 'Inlandsverwendung_Veraenderung_%']

Finaldatei erfolgreich gespeichert:
C:\Users\incog\Desktop\Portfolio_Project_Agriculture\data\processed\ble_supply_balance_final_1991-2025.xlsx

In [59]:

import pandas as pd
from pathlib import Path

# --------------------------------------------------
# 1. Dateien laden
# --------------------------------------------------
final_file = Path(final_file)

production_file = (
    final_file.parent / "ble_production_change_1991-2025.xlsx"
)

df_final = pd.read_excel(final_file)
df_prod = pd.read_excel(production_file)

# Spaltennamen vereinheitlichen: Leerzeichen -> Unterstriche
for df in [df_final, df_prod]:
    df.columns = (
        df.columns.astype(str)
        .str.strip()
        .str.replace(r"\s+", "_", regex=True)
    )

print("Finaldatei:", df_final.shape)
print("Production-Change-Datei:", df_prod.shape)

# --------------------------------------------------
# 2. Schlüssel prüfen
# --------------------------------------------------
keys = ["Wirtschaftsjahr", "Bilanz_Produkt"]

for key in keys:
    if key not in df_final.columns:
        raise KeyError(f"Schlüssel fehlt in Finaldatei: {key}")
    if key not in df_prod.columns:
        raise KeyError(f"Schlüssel fehlt in Production-Datei: {key}")

# Die letzten beiden Spalten der Production-Datei
source_cols = list(df_prod.columns[-2:])

if any(col in keys for col in source_cols):
    raise ValueError(
        f"Die letzten beiden Spalten sind nicht beide Daten-Spalten: "
        f"{source_cols}"
    )

print("\nLetzte zwei Spalten der Production-Datei:")
print(source_cols)

# --------------------------------------------------
# 3. Spalten auswählen und umbenennen
# --------------------------------------------------
rename_map = {
    source_cols[0]: "Verwendbare_Erzeugung_Vorjahr",
    source_cols[1]: "Verwendbare_Erzeugung_Veraenderung_%"
}

df_prod_subset = df_prod[keys + source_cols].rename(
    columns=rename_map
)

target_cols = list(rename_map.values())

# Doppelte Schlüssel verhindern
if df_final.duplicated(keys).any():
    raise ValueError("Die Finaldatei enthält doppelte Schlüssel.")

if df_prod_subset.duplicated(keys).any():
    raise ValueError(
        "Die Production-Datei enthält doppelte Schlüssel."
    )

# Vorhandene Zielspalten ersetzen, falls sie bereits existieren
df_final = df_final.drop(
    columns=target_cols,
    errors="ignore"
)

# --------------------------------------------------
# 4. Merge durchführen
# --------------------------------------------------
df_merged = df_final.merge(
    df_prod_subset,
    on=keys,
    how="left",
    validate="one_to_one",
    indicator=True
)

matched = (df_merged["_merge"] == "both").sum()
unmatched = (df_merged["_merge"] == "left_only").sum()

print("\n=== Merge-Ergebnis ===")
print("Zeilen vorher:", len(df_final))
print("Zeilen nachher:", len(df_merged))
print("Zuordnungen:", matched)
print("Ohne Quelldatensatz:", unmatched)

# Nicht speichern, wenn Zuordnungen fehlen oder Zeilenanzahl abweicht
if len(df_merged) != len(df_final):
    raise ValueError("Die Zeilenanzahl hat sich verändert.")

if unmatched > 0:
    print("\nNicht zugeordnete Datensätze:")
    display(
        df_merged.loc[
            df_merged["_merge"] == "left_only",
            keys
        ]
    )
    raise ValueError(
        "Es fehlen Zuordnungen. Die Finaldatei wurde nicht gespeichert."
    )

# --------------------------------------------------
# 5. Ergebnis prüfen und speichern
# --------------------------------------------------
df_merged = df_merged.drop(columns="_merge")

print("\nNeue Spalten:")
display(df_merged[keys + target_cols].head(10))

df_merged.to_excel(final_file, index=False)

print("\nFinaldatei erfolgreich aktualisiert:")
print(final_file)
print("Neue Dimensionen:", df_merged.shape)

Finaldatei: (102, 45)
Production-Change-Datei: (102, 5)

Letzte zwei Spalten der Production-Datei:
['Vorjahr', 'Veränderung_in_%']

=== Merge-Ergebnis ===
Zeilen vorher: 102
Zeilen nachher: 102
Zuordnungen: 102
Ohne Quelldatensatz: 0

Neue Spalten:

,Wirtschaftsjahr,Bilanz_Produkt,Verwendbare_Erzeugung_Vorjahr,Verwendbare_Erzeugung_Veraenderung_%
0,1991/92,Gerste,NaN,NaN
1,1991/92,Kartoffeln,NaN,NaN
2,1991/92,Weichweizen,NaN,NaN
3,1992/93,Gerste,14494.0,-15.854836
4,1992/93,Kartoffeln,9737.0,6.377734
5,1992/93,Weichweizen,16531.0,-6.406146
6,1993/94,Gerste,12196.0,-9.757297
7,1993/94,Kartoffeln,10358.0,12.309326
8,1993/94,Weichweizen,15472.0,1.602896
9,1994/95,Gerste,11006.0,-2.326004

Finaldatei erfolgreich aktualisiert:
C:\Users\incog\Desktop\Portfolio_Project_Agriculture\data\processed\ble_supply_balance_final_1991-2025.xlsx
Neue Dimensionen: (102, 47)

In [60]:
df_verify = pd.read_excel(final_file)

cols = [
    "Verwendbare_Erzeugung_Vorjahr",
    "Verwendbare_Erzeugung_Veraenderung_%"
]

print("Dimensionen:", df_verify.shape)
print("\nFehlende Werte:")
print(df_verify[cols].isna().sum())

display(
    df_verify[
        ["Wirtschaftsjahr", "Bilanz_Produkt"] + cols
    ].head(12)
)

Dimensionen: (102, 47)

Fehlende Werte:
Verwendbare_Erzeugung_Vorjahr           3
Verwendbare_Erzeugung_Veraenderung_%    3
dtype: int64

,Wirtschaftsjahr,Bilanz_Produkt,Verwendbare_Erzeugung_Vorjahr,Verwendbare_Erzeugung_Veraenderung_%
0,1991/92,Gerste,NaN,NaN
1,1991/92,Kartoffeln,NaN,NaN
2,1991/92,Weichweizen,NaN,NaN
3,1992/93,Gerste,14494.0,-15.854836
4,1992/93,Kartoffeln,9737.0,6.377734
5,1992/93,Weichweizen,16531.0,-6.406146
6,1993/94,Gerste,12196.0,-9.757297
7,1993/94,Kartoffeln,10358.0,12.309326
8,1993/94,Weichweizen,15472.0,1.602896
9,1994/95,Gerste,11006.0,-2.326004
10,1994/95,Kartoffeln,11633.0,-15.885842
11,1994/95,Weichweizen,15720.0,2.907125